// @generated by oracle/scripts/gen_bgc_zero_fluxes.py from vendor/CoLM202X/main/BGC/MOD_BGC_CNZeroFluxes.F90.
// Do not edit by hand; rerun the generator after the upstream source changes.
#![allow(clippy::all)]

use crate::bgc_state::BgcState;

/// 生成器需要的开关（`#ifdef CROP` 与 `DEF_USE_NITRIF`）。
#[derive(Debug, Clone, Copy)]
pub struct ZeroFluxSwitches {
    pub crop: bool,
    pub use_nitrif: bool,
}

/// `CNZeroFluxes`：每步开头把 BGC 通量清零。
pub fn cn_zero_fluxes(s: &mut BgcState, ctx: ZeroFluxSwitches) {
    let d = s.dims;
    let npft = s.pft_flux.cpool_to_leafc_p.len();
    for m in 0..npft {
        s.pft_flux.m_leafc_to_litter_p[m] = 0.0;
        s.pft_flux.m_frootc_to_litter_p[m] = 0.0;
        s.pft_flux.m_leafc_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_frootc_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_livestemc_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadstemc_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_livecrootc_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadcrootc_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_leafc_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_frootc_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_livestemc_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadstemc_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_livecrootc_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadcrootc_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_livestemc_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadstemc_to_litter_p[m] = 0.0;
        s.pft_flux.m_livecrootc_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadcrootc_to_litter_p[m] = 0.0;
        s.pft_flux.m_gresp_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_gresp_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_leafc_to_fire_p[m] = 0.0;
        s.pft_flux.m_leafc_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_leafc_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_livestemc_to_fire_p[m] = 0.0;
        s.pft_flux.m_livestemc_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_livestemc_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemc_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemc_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemc_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_frootc_to_fire_p[m] = 0.0;
        s.pft_flux.m_frootc_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_frootc_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootc_to_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootc_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootc_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootc_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootc_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootc_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_gresp_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_gresp_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_leafc_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_leafc_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_leafc_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livestemc_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livestemc_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livestemc_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livestemc_to_deadstemc_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemc_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemc_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemc_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_frootc_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_frootc_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_frootc_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootc_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootc_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootc_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootc_to_deadcrootc_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootc_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootc_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootc_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_gresp_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_gresp_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.leafc_xfer_to_leafc_p[m] = 0.0;
        s.pft_flux.frootc_xfer_to_frootc_p[m] = 0.0;
        s.pft_flux.livestemc_xfer_to_livestemc_p[m] = 0.0;
        s.pft_flux.deadstemc_xfer_to_deadstemc_p[m] = 0.0;
        s.pft_flux.livecrootc_xfer_to_livecrootc_p[m] = 0.0;
        s.pft_flux.deadcrootc_xfer_to_deadcrootc_p[m] = 0.0;
        s.pft_flux.leafc_to_litter_p[m] = 0.0;
        s.pft_flux.frootc_to_litter_p[m] = 0.0;
        s.pft_flux.leaf_mr_p[m] = 0.0;
        s.pft_flux.froot_mr_p[m] = 0.0;
        s.pft_flux.livestem_mr_p[m] = 0.0;
        s.pft_flux.livecroot_mr_p[m] = 0.0;
        s.pft_flux.grain_mr_p[m] = 0.0;
        s.pft_flux.leaf_curmr_p[m] = 0.0;
        s.pft_flux.froot_curmr_p[m] = 0.0;
        s.pft_flux.livestem_curmr_p[m] = 0.0;
        s.pft_flux.livecroot_curmr_p[m] = 0.0;
        s.pft_flux.grain_curmr_p[m] = 0.0;
        s.pft_flux.leaf_xsmr_p[m] = 0.0;
        s.pft_flux.froot_xsmr_p[m] = 0.0;
        s.pft_flux.livestem_xsmr_p[m] = 0.0;
        s.pft_flux.livecroot_xsmr_p[m] = 0.0;
        s.pft_flux.grain_xsmr_p[m] = 0.0;
        s.pft_flux.psn_to_cpool_p[m] = 0.0;
        s.pft_flux.cpool_to_xsmrpool_p[m] = 0.0;
        s.pft_flux.cpool_to_leafc_p[m] = 0.0;
        s.pft_flux.cpool_to_leafc_storage_p[m] = 0.0;
        s.pft_flux.cpool_to_frootc_p[m] = 0.0;
        s.pft_flux.cpool_to_frootc_storage_p[m] = 0.0;
        s.pft_flux.cpool_to_livestemc_p[m] = 0.0;
        s.pft_flux.cpool_to_livestemc_storage_p[m] = 0.0;
        s.pft_flux.cpool_to_deadstemc_p[m] = 0.0;
        s.pft_flux.cpool_to_deadstemc_storage_p[m] = 0.0;
        s.pft_flux.cpool_to_livecrootc_p[m] = 0.0;
        s.pft_flux.cpool_to_livecrootc_storage_p[m] = 0.0;
        s.pft_flux.cpool_to_deadcrootc_p[m] = 0.0;
        s.pft_flux.cpool_to_deadcrootc_storage_p[m] = 0.0;
        s.pft_flux.cpool_to_gresp_storage_p[m] = 0.0;
        s.pft_flux.cpool_leaf_gr_p[m] = 0.0;
        s.pft_flux.cpool_leaf_storage_gr_p[m] = 0.0;
        s.pft_flux.transfer_leaf_gr_p[m] = 0.0;
        s.pft_flux.cpool_froot_gr_p[m] = 0.0;
        s.pft_flux.cpool_froot_storage_gr_p[m] = 0.0;
        s.pft_flux.transfer_froot_gr_p[m] = 0.0;
        s.pft_flux.cpool_livestem_gr_p[m] = 0.0;
        s.pft_flux.cpool_livestem_storage_gr_p[m] = 0.0;
        s.pft_flux.transfer_livestem_gr_p[m] = 0.0;
        s.pft_flux.cpool_deadstem_gr_p[m] = 0.0;
        s.pft_flux.cpool_deadstem_storage_gr_p[m] = 0.0;
        s.pft_flux.transfer_deadstem_gr_p[m] = 0.0;
        s.pft_flux.cpool_livecroot_gr_p[m] = 0.0;
        s.pft_flux.cpool_livecroot_storage_gr_p[m] = 0.0;
        s.pft_flux.transfer_livecroot_gr_p[m] = 0.0;
        s.pft_flux.cpool_deadcroot_gr_p[m] = 0.0;
        s.pft_flux.cpool_deadcroot_storage_gr_p[m] = 0.0;
        s.pft_flux.transfer_deadcroot_gr_p[m] = 0.0;
        s.pft_flux.leafc_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.frootc_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.livestemc_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.deadstemc_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.livecrootc_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.deadcrootc_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.gresp_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.livestemc_to_deadstemc_p[m] = 0.0;
        s.pft_flux.livecrootc_to_deadcrootc_p[m] = 0.0;
        s.pft_flux.crop_seedc_to_leaf_p[m] = 0.0;
        s.pft_flux.hrv_xsmrpool_to_atm_p[m] = 0.0;
        s.pft_flux.xsmrpool_to_atm_p[m] = 0.0;
        s.pft_flux.livestemc_to_litter_p[m] = 0.0;
        s.pft_flux.grainc_to_food_p[m] = 0.0;
        s.pft_flux.grainc_to_seed_p[m] = 0.0;
        s.pft_flux.grainc_xfer_to_grainc_p[m] = 0.0;
        s.pft_flux.cpool_to_grainc_p[m] = 0.0;
        s.pft_flux.cpool_to_grainc_storage_p[m] = 0.0;
        s.pft_flux.cpool_grain_gr_p[m] = 0.0;
        s.pft_flux.cpool_grain_storage_gr_p[m] = 0.0;
        s.pft_flux.transfer_grain_gr_p[m] = 0.0;
        s.pft_flux.grainc_storage_to_xfer_p[m] = 0.0;
    }
    for j in 0..d.nl_soil {
        s.patch_flux.phenology_to_met_c[j] = 0.0;
        s.patch_flux.phenology_to_cel_c[j] = 0.0;
        s.patch_flux.phenology_to_lig_c[j] = 0.0;
        s.patch_flux.gap_mortality_to_met_c[j] = 0.0;
        s.patch_flux.gap_mortality_to_cel_c[j] = 0.0;
        s.patch_flux.gap_mortality_to_lig_c[j] = 0.0;
        s.patch_flux.gap_mortality_to_cwdc[j] = 0.0;
        s.patch_flux.fire_mortality_to_cwdc[j] = 0.0;
        s.patch_flux.fire_mortality_to_met_c[j] = 0.0;
        s.patch_flux.fire_mortality_to_cel_c[j] = 0.0;
        s.patch_flux.fire_mortality_to_lig_c[j] = 0.0;
        for k in 0..d.ndecomp_pools {
            s.patch_flux.m_decomp_cpools_to_fire_vr[j + d.nl_soil_full * k] = 0.0;
        }
    }
    s.patch_flux.fire_closs[0] = 0.0;
    s.patch_flux.fire_nloss[0] = 0.0;
    s.patch_flux.wood_harvestc[0] = 0.0;
    s.patch_flux.wood_harvestn[0] = 0.0;
    s.patch_flux.grainc_to_cropprodc[0] = 0.0;
    s.patch_flux.grainn_to_cropprodn[0] = 0.0;
    for m in 0..npft {
        s.pft_flux.gpp_p[m] = 0.0;
        s.pft_flux.wood_harvestc_p[m] = 0.0;
        s.pft_flux.wood_harvestn_p[m] = 0.0;
        s.pft_flux.grainc_to_cropprodc_p[m] = 0.0;
        s.pft_flux.grainn_to_cropprodn_p[m] = 0.0;
        s.pft_flux.soyfixn_p[m] = 0.0;
        s.pft_flux.fire_closs_p[m] = 0.0;
        s.pft_flux.fire_nloss_p[m] = 0.0;
        s.pft_flux.m_leafn_to_litter_p[m] = 0.0;
        s.pft_flux.m_frootn_to_litter_p[m] = 0.0;
        s.pft_flux.m_leafn_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_frootn_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_livestemn_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadstemn_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_livecrootn_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadcrootn_storage_to_litter_p[m] = 0.0;
        s.pft_flux.m_leafn_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_frootn_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_livestemn_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadstemn_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_livecrootn_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadcrootn_xfer_to_litter_p[m] = 0.0;
        s.pft_flux.m_livestemn_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadstemn_to_litter_p[m] = 0.0;
        s.pft_flux.m_livecrootn_to_litter_p[m] = 0.0;
        s.pft_flux.m_deadcrootn_to_litter_p[m] = 0.0;
        s.pft_flux.m_retransn_to_litter_p[m] = 0.0;
        s.pft_flux.m_leafn_to_fire_p[m] = 0.0;
        s.pft_flux.m_leafn_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_leafn_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_livestemn_to_fire_p[m] = 0.0;
        s.pft_flux.m_livestemn_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_livestemn_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemn_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemn_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemn_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_frootn_to_fire_p[m] = 0.0;
        s.pft_flux.m_frootn_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_frootn_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootn_to_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootn_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootn_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootn_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootn_storage_to_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootn_xfer_to_fire_p[m] = 0.0;
        s.pft_flux.m_retransn_to_fire_p[m] = 0.0;
        s.pft_flux.m_leafn_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_leafn_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_leafn_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livestemn_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livestemn_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livestemn_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livestemn_to_deadstemn_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemn_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemn_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_deadstemn_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_frootn_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_frootn_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_frootn_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootn_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootn_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootn_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_livecrootn_to_deadcrootn_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootn_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootn_storage_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_deadcrootn_xfer_to_litter_fire_p[m] = 0.0;
        s.pft_flux.m_retransn_to_litter_fire_p[m] = 0.0;
        s.pft_flux.leafn_xfer_to_leafn_p[m] = 0.0;
        s.pft_flux.frootn_xfer_to_frootn_p[m] = 0.0;
        s.pft_flux.livestemn_xfer_to_livestemn_p[m] = 0.0;
        s.pft_flux.deadstemn_xfer_to_deadstemn_p[m] = 0.0;
        s.pft_flux.livecrootn_xfer_to_livecrootn_p[m] = 0.0;
        s.pft_flux.deadcrootn_xfer_to_deadcrootn_p[m] = 0.0;
        s.pft_flux.leafn_to_litter_p[m] = 0.0;
        s.pft_flux.leafn_to_retransn_p[m] = 0.0;
        s.pft_flux.frootn_to_litter_p[m] = 0.0;
        s.pft_flux.retransn_to_npool_p[m] = 0.0;
        s.pft_flux.free_retransn_to_npool_p[m] = 0.0;
        s.pft_flux.sminn_to_npool_p[m] = 0.0;
        s.pft_flux.npool_to_leafn_p[m] = 0.0;
        s.pft_flux.npool_to_leafn_storage_p[m] = 0.0;
        s.pft_flux.npool_to_frootn_p[m] = 0.0;
        s.pft_flux.npool_to_frootn_storage_p[m] = 0.0;
        s.pft_flux.npool_to_livestemn_p[m] = 0.0;
        s.pft_flux.npool_to_livestemn_storage_p[m] = 0.0;
        s.pft_flux.npool_to_deadstemn_p[m] = 0.0;
        s.pft_flux.npool_to_deadstemn_storage_p[m] = 0.0;
        s.pft_flux.npool_to_livecrootn_p[m] = 0.0;
        s.pft_flux.npool_to_livecrootn_storage_p[m] = 0.0;
        s.pft_flux.npool_to_deadcrootn_p[m] = 0.0;
        s.pft_flux.npool_to_deadcrootn_storage_p[m] = 0.0;
        s.pft_flux.leafn_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.frootn_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.livestemn_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.deadstemn_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.livecrootn_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.deadcrootn_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.livestemn_to_deadstemn_p[m] = 0.0;
        s.pft_flux.livestemn_to_retransn_p[m] = 0.0;
        s.pft_flux.livecrootn_to_deadcrootn_p[m] = 0.0;
        s.pft_flux.livecrootn_to_retransn_p[m] = 0.0;
        s.pft_flux.crop_seedn_to_leaf_p[m] = 0.0;
        s.pft_flux.livestemn_to_litter_p[m] = 0.0;
        s.pft_flux.grainn_to_food_p[m] = 0.0;
        s.pft_flux.grainn_to_seed_p[m] = 0.0;
        s.pft_flux.grainn_xfer_to_grainn_p[m] = 0.0;
        s.pft_flux.npool_to_grainn_p[m] = 0.0;
        s.pft_flux.npool_to_grainn_storage_p[m] = 0.0;
        s.pft_flux.grainn_storage_to_xfer_p[m] = 0.0;
        s.pft_flux.frootn_to_retransn_p[m] = 0.0;
    }
    for j in 0..d.nl_soil {
        s.patch_flux.phenology_to_met_n[j] = 0.0;
        s.patch_flux.phenology_to_cel_n[j] = 0.0;
        s.patch_flux.phenology_to_lig_n[j] = 0.0;
        s.patch_flux.gap_mortality_to_met_n[j] = 0.0;
        s.patch_flux.gap_mortality_to_cel_n[j] = 0.0;
        s.patch_flux.gap_mortality_to_lig_n[j] = 0.0;
        s.patch_flux.gap_mortality_to_cwdn[j] = 0.0;
        s.patch_flux.fire_mortality_to_cwdn[j] = 0.0;
        s.patch_flux.fire_mortality_to_met_n[j] = 0.0;
        s.patch_flux.fire_mortality_to_cel_n[j] = 0.0;
        s.patch_flux.fire_mortality_to_lig_n[j] = 0.0;
    }
    for k in 0..d.ndecomp_pools {
        for j in 0..d.nl_soil {
            s.patch_flux.m_decomp_npools_to_fire_vr[j + d.nl_soil_full * k] = 0.0;
        }
    }
    for k in 0..d.ndecomp_transitions {
        for j in 0..d.nl_soil {
            s.patch_flux.decomp_hr_vr[j + d.nl_soil_full * k] = 0.0;
            s.patch_flux.decomp_ctransfer_vr[j + d.nl_soil_full * k] = 0.0;
        }
    }
    for k in 0..d.ndecomp_pools {
        for j in 0..d.nl_soil {
            s.patch_flux.decomp_cpools_transport_tendency[j + d.nl_soil_full * k] = 0.0;
            s.patch_flux.decomp_cpools_sourcesink[j + d.nl_soil_full * k] = 0.0;
            s.patch.decomp_k[j + d.nl_soil_full * k] = 0.0;
        }
    }
    s.patch_flux.somc_fire[0] = 0.0;
    s.patch_flux.som_c_leached[0] = 0.0;
    s.patch_flux.decomp_hr[0] = 0.0;
    if !ctx.use_nitrif {
        for j in 0..d.nl_soil {
            s.patch_flux.sminn_to_denit_excess_vr[j] = 0.0;
            s.patch_flux.sminn_leached_vr[j] = 0.0;
            s.patch_flux.sminn_to_plant_fun_vr[j] = 0.0;
        }
    } else {
        for j in 0..d.nl_soil {
            s.patch_flux.f_nit_vr[j] = 0.0;
            s.patch_flux.f_denit_vr[j] = 0.0;
            s.patch_flux.smin_no3_leached_vr[j] = 0.0;
            s.patch_flux.smin_no3_runoff_vr[j] = 0.0;
            s.patch_flux.n2_n2o_ratio_denit_vr[j] = 0.0;
            s.patch_flux.pot_f_nit_vr[j] = 0.0;
            s.patch_flux.pot_f_denit_vr[j] = 0.0;
            s.patch_flux.actual_immob_no3_vr[j] = 0.0;
            s.patch_flux.actual_immob_nh4_vr[j] = 0.0;
            s.patch_flux.smin_no3_to_plant_vr[j] = 0.0;
            s.patch_flux.smin_nh4_to_plant_vr[j] = 0.0;
            s.patch_flux.f_n2o_denit_vr[j] = 0.0;
            s.patch_flux.f_n2o_nit_vr[j] = 0.0;
        }
    }
    for j in 0..d.nl_soil {
        s.patch_flux.potential_immob_vr[j] = 0.0;
        s.patch_flux.actual_immob_vr[j] = 0.0;
        s.patch_flux.sminn_to_plant[0] = 0.0;
        s.patch_flux.sminn_to_plant_vr[j] = 0.0;
        s.patch_flux.supplement_to_sminn_vr[j] = 0.0;
        s.patch_flux.gross_nmin_vr[j] = 0.0;
        s.patch_flux.net_nmin_vr[j] = 0.0;
        s.patch_flux.sminn_to_plant_fun_no3_vr[j] = 0.0;
        s.patch_flux.sminn_to_plant_fun_nh4_vr[j] = 0.0;
    }
    s.patch_flux.nfix_to_sminn[0] = 0.0;
    s.patch_flux.ffix_to_sminn[0] = 0.0;
    s.patch_flux.fert_to_sminn[0] = 0.0;
    s.patch_flux.soyfixn_to_sminn[0] = 0.0;
    s.patch_flux.supplement_to_sminn[0] = 0.0;
    s.patch_flux.gross_nmin[0] = 0.0;
    s.patch_flux.net_nmin[0] = 0.0;
    s.patch_flux.denit[0] = 0.0;
    s.patch_flux.f_n2o_nit[0] = 0.0;
    s.patch_flux.smin_no3_leached[0] = 0.0;
    s.patch_flux.smin_no3_runoff[0] = 0.0;
    s.patch_flux.sminn_leached[0] = 0.0;
    s.patch_flux.som_n_leached[0] = 0.0;
    for k in 0..d.ndecomp_pools {
        for j in 0..d.nl_soil {
            s.patch_flux.decomp_npools_transport_tendency[j + d.nl_soil_full * k] = 0.0;
        }
    }
    for k in 0..d.ndecomp_transitions {
        for j in 0..d.nl_soil {
            s.patch_flux.decomp_ntransfer_vr[j + d.nl_soil_full * k] = 0.0;
            s.patch_flux.decomp_sminn_flux_vr[j + d.nl_soil_full * k] = 0.0;
        }
    }
    if !ctx.use_nitrif {
        for k in 0..d.ndecomp_transitions {
            for j in 0..d.nl_soil {
                s.patch_flux.sminn_to_denit_decomp_vr[j + d.nl_soil_full * k] = 0.0;
            }
        }
    }
    for k in 0..d.ndecomp_pools {
        for j in 0..d.nl_soil {
            s.patch_flux.decomp_npools_sourcesink[j + d.nl_soil_full * k] = 0.0;
        }
    }
}
