#!/usr/bin/env python3
"""生成 vendor/CoLM202X/Makefile 末尾的同阶段 Fortran 模块依赖块。

上游 Makefile 只靠对象在阶段变量里的排列顺序保证模块先编译，串行 make 能过、`make -j` 不安全。
这里按源码的 MODULE/USE 推出**同一阶段内**的 `.o -> .o` 前置；跨阶段的顺序已由模式规则里的
`${OBJS_SHARED}` 等前置保证，不再重复。

阶段 = Makefile 里每条 `$(VAR) : %.o : %.F90 ...` 模式规则的目标列表；变量值交给 make 自己展开
（含 `+=`、嵌套变量与 `$(addprefix ...)`），不在这里重写一遍 make 的语义。

    python3 oracle/scripts/gen_fortran_deps.py            # 重写 Makefile 里的生成块
    python3 oracle/scripts/gen_fortran_deps.py --check    # 只比对，不一致时返回 1

同步上游之后必须重跑本脚本（见 vendor/PROVENANCE.md）。
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
VENDOR = os.path.join(REPO, "vendor", "CoLM202X")
MAKEFILE = os.path.join(VENDOR, "Makefile")
BEGIN = "# >>> generated by oracle/scripts/gen_fortran_deps.py -- do not edit by hand >>>"
END = "# <<< end of generated Fortran module prerequisites <<<"
MODULE_DEF = re.compile(r"^\s*module\s+(?!procedure\b)([a-z0-9_]+)\s*$", re.IGNORECASE)
USE_STMT = re.compile(r"^\s*use\s*(?:,\s*(intrinsic|non_intrinsic)\s*::|::)?\s*([a-z0-9_]+)", re.IGNORECASE)


def stage_variables(makefile_text):
    """每条 `$(VAR) : %.o : %.F90` 规则左侧的变量名（`$(filter-out X,$(VAR))` 取其中的 VAR）。"""
    names = []
    for line in makefile_text.splitlines():
        normalized = line.replace("${", "$(").replace("}", ")")
        match = re.match(r"^(\$\(.*?)\s*:\s*%\.o\s*:\s*%\.F90", normalized)
        if not match:
            continue
        variables = re.findall(r"\$\(([A-Za-z0-9_]+)\)", match.group(1))
        if variables:
            names.append(variables[-1])
    return names


def expand(variable):
    """让 make 展开一个变量（在 vendor 目录下，读真实的 include/Makeoptions）。"""
    with tempfile.NamedTemporaryFile("w", suffix=".mk", delete=False) as helper:
        helper.write("print-%:\n\t@echo $($*)\n")
        path = helper.name
    try:
        result = subprocess.run(
            ["make", "-s", "-f", "Makefile", "-f", path, f"print-{variable}"],
            cwd=VENDOR, check=True, capture_output=True, text=True)
    finally:
        os.unlink(path)
    return [word for word in result.stdout.split() if word.endswith(".o")]


def vpath_directories(makefile_text):
    match = re.search(r"^VPATH\s*=\s*((?:.*\\\n)*.*)$", makefile_text, re.MULTILINE)
    text = match.group(1).replace("\\\n", " ")
    return [part.strip() for part in text.split(":") if part.strip()]


def find_source(obj, directories):
    stem = obj[:-2]
    for directory in directories:
        path = os.path.join(VENDOR, directory, stem + ".F90")
        if os.path.isfile(path):
            return path
    return None


def scan(path):
    """一个源文件定义的模块与 USE 的模块（小写；`#ifdef` 两支都算）。"""
    defined, used = set(), set()
    with open(path, encoding="utf-8", errors="replace") as handle:
        for raw in handle:
            line = raw.split("!", 1)[0]
            match = MODULE_DEF.match(line)
            if match:
                defined.add(match.group(1).lower())
                continue
            match = USE_STMT.match(line)
            if match and (match.group(1) or "").lower() != "intrinsic":
                used.add(match.group(2).lower())
    return defined, used - defined


def generate():
    with open(MAKEFILE, encoding="utf-8") as handle:
        text = handle.read()
    directories = vpath_directories(text)
    lines = []
    variables = stage_variables(text)
    for variable in variables:
        objects = [obj for obj in expand(variable) if obj != "CoLM_Mkdir.o"]
        sources = {obj: find_source(obj, directories) for obj in objects}
        owner, uses = {}, {}
        for obj, path in sources.items():
            if path is None:
                continue
            defined, used = scan(path)
            uses[obj] = used
            for module in defined:
                owner.setdefault(module, obj)
        for obj in sorted(uses):
            deps = sorted({owner[m] for m in uses[obj] if m in owner and owner[m] != obj})
            if deps:
                lines.append(f"{obj}: {' '.join(deps)}")
    # 对象都写进 `.bld/`：并行时要先建好目录（order-only，不触发重编）。
    order_only = [f"$({variable}): | mkdir_build" for variable in variables]
    block = [BEGIN,
             "# Same-stage MODULE/USE prerequisites (cross-stage ordering comes from the pattern",
             "# rules above).  Regenerate after every upstream sync.",
             *order_only,
             *sorted(set(lines)),
             END]
    return text, "\n".join(block) + "\n"


def splice(text, block):
    if BEGIN in text:
        start = text.index(BEGIN)
        end = text.index(END, start) + len(END) + 1
        return text[:start] + block + text[end:]
    return text.rstrip("\n") + "\n\n" + block


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare only; exit 1 on drift")
    args = parser.parse_args()
    text, block = generate()
    updated = splice(text, block)
    if args.check:
        if updated != text:
            print("vendor/CoLM202X/Makefile: generated Fortran module prerequisites are stale; "
                  "run oracle/scripts/gen_fortran_deps.py", file=sys.stderr)
            return 1
        print("generated Fortran module prerequisites are current")
        return 0
    with open(MAKEFILE, "w", encoding="utf-8") as handle:
        handle.write(updated)
    print(f"wrote {block.count(chr(10)) - 4} prerequisite lines to {MAKEFILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
