#!/usr/bin/env python3
"""Generate crates/colm-core/src/methane/config_generated.rs from the
Methane_type / Methane_hydrology_type declarations in
vendor/CoLM202X/main/TRACER/MOD_Tracer_Reactive_Methane_Const.F90."""
import re, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
src = (root / 'vendor/CoLM202X/main/TRACER/MOD_Tracer_Reactive_Methane_Const.F90').read_text()

def block(name):
    return re.search(r'type\s+' + name + r'\s*\n(.*?)END type', src, re.S | re.I).group(1)

def fields(b):
    out = []
    for line in b.splitlines():
        line = line.split('!')[0].strip()
        if not line:
            continue
        m = re.match(r'(real\(r8\)|logical|integer|character\(len=\d+\))\s*::\s*(\w+)\s*=\s*(.+)$', line, re.I)
        if not m:
            raise SystemExit('cannot parse: ' + line)
        t, n, v = m.groups()
        v = v.strip()
        t = t.lower()
        if t.startswith('real'):
            v = re.sub(r'_r8', '', v)
            v = re.sub(r'(\d)\.(?=[^\d]|$)', r'\1.0', v)
            kind = 'f64'
        elif t == 'logical':
            v, kind = ('true' if v.lower() == '.true.' else 'false'), 'bool'
        elif t == 'integer':
            kind = 'i32'
        else:
            v, kind = '"%s".to_owned()' % v.strip("'\""), 'String'
        out.append((n.lower(), kind, v))
    return out

conv = {'f64': 'value.real(path)?', 'bool': 'value.logical(path)?',
        'i32': 'value.int(path)?', 'String': 'value.text(path)?'}
lines = ['// @generated by oracle/scripts/gen_methane_config.py from',
         '// vendor/CoLM202X/main/TRACER/MOD_Tracer_Reactive_Methane_Const.F90 (Methane_type, Methane_hydrology_type).',
         '// Do not edit by hand; rerun the generator after the upstream declarations change.',
         '#![allow(clippy::excessive_precision)]', '',
         'use anyhow::Result;', '',
         'use super::config::FieldValue;', '']
for tname, b, doc in [('MethaneConfig', 'Methane_type', '`Methane_type`（`DEF_METHANE`）。'),
                      ('MethaneHydrology', 'Methane_hydrology_type', '`Methane_hydrology_type`（`DEF_METHANE_hydrology`）。')]:
    fl = fields(block(b))
    lines += ['/// ' + doc, '#[derive(Debug, Clone, PartialEq)]', 'pub struct %s {' % tname]
    lines += ['    pub %s: %s,' % (n, k) for n, k, _ in fl]
    lines += ['}', '', 'impl Default for %s {' % tname, '    fn default() -> Self {', '        Self {']
    lines += ['            %s: %s,' % (n, v) for n, _, v in fl]
    lines += ['        }', '    }', '}', '', 'impl %s {' % tname,
              '    /// 按小写字段名赋值；未知名字返回 `false`。',
              '    pub fn set(&mut self, name: &str, value: &FieldValue, path: &str) -> Result<bool> {',
              '        match name {']
    lines += ['            "%s" => self.%s = %s,' % (n, n, conv[k]) for n, k, _ in fl]
    lines += ['            _ => return Ok(false),', '        }', '        Ok(true)', '    }', '}', '']
(root / 'crates/colm-core/src/methane/config_generated.rs').write_text('\n'.join(lines))
