#!/usr/bin/env python3
"""Generate crates/colm-runtime/src/methane_restart_generated.rs: the ordered
`ch4_a_*` accumulator fields that write_methane_accflux_restart writes when
the microbial pools are off (MOD_Tracer_Reactive_Methane_AccFlux.F90)."""
import re, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
src = (root / 'vendor/CoLM202X/main/TRACER/MOD_Tracer_Reactive_Methane_AccFlux.F90').read_text()
body = re.search(r'SUBROUTINE write_methane_accflux_restart(.*?)END SUBROUTINE write_methane_accflux_restart', src, re.S).group(1)
body = '\n'.join(l for l in body.splitlines() if not l.strip().startswith('!'))
body = re.sub(r'&\s*\n\s*', '', body)
microbe = re.compile(r'B_methan|f_T_|f_S_|f_O2_|growth_rate|microbial_|acc_num_microbe')
fields = []
for m in re.finditer(r"ncio_write_vector\s*\(\s*file_restart,\s*'(ch4_a_\w+)',\s*('soil')?", body):
    name, layered = m.group(1), m.group(2) is not None
    if microbe.search(name):
        continue
    fields.append((name, layered))
lines = ['// @generated by oracle/scripts/gen_methane_restart.py from',
         '// vendor/CoLM202X/main/TRACER/MOD_Tracer_Reactive_Methane_AccFlux.F90 (write_methane_accflux_restart).',
         '// Do not edit by hand; rerun the generator after the upstream writer changes.', '',
         '/// `write_methane_accflux_restart` 在不开微生物库时写的累加量：`(名字, 是否带 soil 维)`，写出顺序。',
         'pub const ACCFLUX_FIELDS: &[(&str, bool)] = &[']
lines += ['    ("%s", %s),' % (n, 'true' if l else 'false') for n, l in fields]
lines += ['];', '']
(root / 'crates/colm-runtime/src/methane_restart_generated.rs').write_text('\n'.join(lines))
print(len(fields))
