#!/usr/bin/env python3
"""把 `MOD_BGC_CNZeroFluxes.F90:CNZeroFluxes` 转写成 Rust。

生成物 `crates/colm-core/src/bgc_zero_fluxes_generated.rs`，**不要手改**。

`CNZeroFluxes` 的 331 条语句全是 `x(idx) = 0._r8`，只有四种下标形式：
`x(m)`（PFT 循环）、`x(i)`（patch 标量）、`x(j,i)`、`x(j,k,i)`（层 × 池/转化），外加
`#ifdef CROP` 与 `IF (DEF_USE_NITRIF)` 两种分支。逐条手抄既慢又容易漏一条或把
`nl_soil_full` 维的数组清到 15 层（上游只清循环到的 `nl_soil` 层）。
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "vendor/CoLM202X/main/BGC/MOD_BGC_CNZeroFluxes.F90"
OUT = ROOT / "crates/colm-core/src/bgc_zero_fluxes_generated.rs"



def field_owners():
    """直接解析上游声明（生成的 Rust 会被 rustfmt 折行，不适合再解析）。"""
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import gen_bgc_state

    member_of = {
        "BgcPftTimeVariables": "pft",
        "BgcPftFluxes": "pft_flux",
        "BgcPatchTimeVariables": "patch",
        "BgcPatchFluxes": "patch_flux",
        "BgcPatchTimeInvariants": "invariants",
    }
    owners, shapes = {}, {}
    for file, struct, _ in gen_bgc_state.MODULES:
        for name, _, shape, _ in gen_bgc_state.parse(gen_bgc_state.BGC / file):
            owners[name] = member_of[struct]
            shapes[name] = shape
    return owners, shapes


DIM = {"nl_soil": "d.nl_soil", "nl_soil_full": "d.nl_soil_full",
       "ndecomp_pools": "d.ndecomp_pools", "ndecomp_transitions": "d.ndecomp_transitions"}


def main():
    owners, shapes = field_owners()
    lines = SRC.read_text().splitlines()
    start = next(i for i, l in enumerate(lines) if "SUBROUTINE CNZeroFluxes" in l)
    body = []
    loops = {}  # var -> range bound expression
    indent = 1
    out = []

    def emit(text):
        out.append("    " * indent + text)

    for raw in lines[start + 1:]:
        line = raw.split("!")[0].rstrip()
        s = line.strip()
        if not s or s.startswith(("integer", "USE", "IMPLICIT")):
            continue
        low = s.lower()
        if low.startswith("end subroutine"):
            break
        if low.startswith("#ifdef crop"):
            emit("if ctx.crop {")
            indent += 1
            continue
        if low.startswith("#else"):
            indent -= 1
            emit("} else {")
            indent += 1
            continue
        if low.startswith("#endif"):
            indent -= 1
            emit("}")
            continue
        m = re.match(r"if\s*\(\s*(\.not\.)?\s*def_use_nitrif\s*\)\s*then", low)
        if m:
            emit(f"if {'!' if m.group(1) else ''}ctx.use_nitrif {{")
            indent += 1
            continue
        if low == "else":
            indent -= 1
            emit("} else {")
            indent += 1
            continue
        if low == "endif" or low == "end if":
            indent -= 1
            emit("}")
            continue
        m = re.match(r"do\s+(\w+)\s*=\s*(\w+)\s*,\s*(\w+)", low)
        if m:
            var, lo, hi = m.groups()
            if var == "m":
                emit("for m in 0..npft {")
            else:
                emit(f"for {var} in 0..{DIM[hi]} {{")
            indent += 1
            continue
        if low == "enddo" or low == "end do":
            indent -= 1
            emit("}")
            continue
        m = re.match(r"(\w+)\s*\(([^)]*)\)\s*=\s*0\.?(_r8)?$", s, re.I)
        if not m:
            raise SystemExit(f"unhandled statement: {s}")
        name, idx = m.group(1), [x.strip().lower() for x in m.group(2).split(",")]
        member = owners[name]
        shape = shapes[name]
        if idx == ["m"]:
            emit(f"s.{member}.{name}[m] = 0.0;")
        elif idx == ["i"]:
            emit(f"s.{member}.{name}[0] = 0.0;")
        elif idx == ["j", "i"]:
            emit(f"s.{member}.{name}[j] = 0.0;")
        elif idx == ["j", "k", "i"]:
            emit(f"s.{member}.{name}[j + {DIM[shape[0]]} * k] = 0.0;")
        else:
            raise SystemExit(f"unhandled index {idx} in {s}")

    header = [
        "// @generated by oracle/scripts/gen_bgc_zero_fluxes.py from vendor/CoLM202X/main/BGC/MOD_BGC_CNZeroFluxes.F90.",
        "// Do not edit by hand; rerun the generator after the upstream source changes.",
        "#![allow(clippy::all)]",
        "",
        "use crate::bgc_state::BgcState;",
        "",
        "/// 生成器需要的开关（`#ifdef CROP` 与 `DEF_USE_NITRIF`）。",
        "#[derive(Debug, Clone, Copy)]",
        "pub struct ZeroFluxSwitches {",
        "    pub crop: bool,",
        "    pub use_nitrif: bool,",
        "}",
        "",
        "/// `CNZeroFluxes`：每步开头把 BGC 通量清零。",
        "pub fn cn_zero_fluxes(s: &mut BgcState, ctx: ZeroFluxSwitches) {",
        "    let d = s.dims;",
        "    let npft = s.pft_flux.cpool_to_leafc_p.len();",
    ]
    OUT.write_text("\n".join(header + out + ["}", ""]))
    print(f"wrote {OUT} ({sum(1 for l in out if '= 0.0;' in l)} assignments)")


if __name__ == "__main__":
    main()
