//! 由 `cargo run -p xtask -- gen-histmap` 生成。**不要手改。**
//!
//! 源：vendor/CoLM202X/main/MOD_Hist.F90
//! 漂移由 crates/colm-hist/tests/drift.rs 守住。

use crate::{Cond, Var};

// 一个变量一行 —— 上游改一处，diff 就只有一行。rustfmt 会把每条拆成
// 六行（456 条 -> 近三千行），那样 code review 里就看不出改了什么了。
// colm-schema 的同类文件不用写这条：它有一条 626 字符、断不开的数组
// 默认值，rustfmt 因此整块放弃 —— 那是巧合，不是设计，这里写明。
#[rustfmt::skip]
pub static VARS: &[Var] = &[
    Var { name: "BD_all", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1866 },
    Var { name: "CONC_O2_UNSAT", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_NITRIF"), line: 1882 },
    Var { name: "O2_DECOMP_DEPTH_UNSAT", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_NITRIF"), line: 1887 },
    Var { name: "OM_density", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1876 },
    Var { name: "abm", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_FIRE"), line: 1894 },
    Var { name: "alb", macros: &[], runtime: None, line: 786 },
    Var { name: "ar", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1351 },
    Var { name: "assim", macros: &[], runtime: None, line: 705 },
    Var { name: "assimsha", macros: &[], runtime: None, line: 1026 },
    Var { name: "assimsun", macros: &[], runtime: None, line: 1020 },
    Var { name: "cphase", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1372 },
    Var { name: "cropprod1c", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1403 },
    Var { name: "cropprod1c_loss", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1408 },
    Var { name: "cropprodc_irrigated_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3885 },
    Var { name: "cropprodc_irrigated_rice", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3945 },
    Var { name: "cropprodc_irrigated_spwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3703 },
    Var { name: "cropprodc_irrigated_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4005 },
    Var { name: "cropprodc_irrigated_temp_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3643 },
    Var { name: "cropprodc_irrigated_temp_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3824 },
    Var { name: "cropprodc_irrigated_trop_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4065 },
    Var { name: "cropprodc_irrigated_trop_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4126 },
    Var { name: "cropprodc_irrigated_wtwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3763 },
    Var { name: "cropprodc_rainfed_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3855 },
    Var { name: "cropprodc_rainfed_rice", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3915 },
    Var { name: "cropprodc_rainfed_spwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3673 },
    Var { name: "cropprodc_rainfed_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3975 },
    Var { name: "cropprodc_rainfed_temp_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3613 },
    Var { name: "cropprodc_rainfed_temp_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3793 },
    Var { name: "cropprodc_rainfed_trop_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4035 },
    Var { name: "cropprodc_rainfed_trop_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4095 },
    Var { name: "cropprodc_rainfed_wtwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3733 },
    Var { name: "cropprodc_unmanagedcrop", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4157 },
    Var { name: "cropseedc_deficit", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1413 },
    Var { name: "cwdcCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1947 },
    Var { name: "cwdc_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1815 },
    Var { name: "cwdnCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1982 },
    Var { name: "cwdn_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1850 },
    Var { name: "deadcrootc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1144 },
    Var { name: "deadcrootcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1659 },
    Var { name: "deadcrootc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1149 },
    Var { name: "deadcrootc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1664 },
    Var { name: "deadcrootc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1155 },
    Var { name: "deadcrootc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1670 },
    Var { name: "deadcrootn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1255 },
    Var { name: "deadcrootnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1759 },
    Var { name: "deadcrootn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1260 },
    Var { name: "deadcrootn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1764 },
    Var { name: "deadcrootn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1266 },
    Var { name: "deadcrootn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1770 },
    Var { name: "deadstemc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1113 },
    Var { name: "deadstemcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1625 },
    Var { name: "deadstemc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1118 },
    Var { name: "deadstemc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1630 },
    Var { name: "deadstemc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1123 },
    Var { name: "deadstemc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1636 },
    Var { name: "deadstemn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1223 },
    Var { name: "deadstemnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1725 },
    Var { name: "deadstemn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1228 },
    Var { name: "deadstemn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1730 },
    Var { name: "deadstemn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1234 },
    Var { name: "deadstemn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1736 },
    Var { name: "discharge", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4785 },
    Var { name: "discharge_rivermouth_regrid", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4790 },
    Var { name: "downreg", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1298 },
    Var { name: "dz_lake", macros: &[], runtime: Some("DEF_USE_Dynamic_Lake"), line: 4531 },
    Var { name: "emis", macros: &[], runtime: None, line: 792 },
    Var { name: "etr", macros: &[], runtime: None, line: 564 },
    Var { name: "etrsha", macros: &[], runtime: None, line: 1037 },
    Var { name: "etrsun", macros: &[], runtime: None, line: 1032 },
    Var { name: "fach", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 963 },
    Var { name: "fert_to_sminn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1433 },
    Var { name: "fertnitro_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2641 },
    Var { name: "fertnitro_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2738 },
    Var { name: "fertnitro_rice1", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2762 },
    Var { name: "fertnitro_rice2", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2786 },
    Var { name: "fertnitro_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2714 },
    Var { name: "fertnitro_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2810 },
    Var { name: "fertnitro_swheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2665 },
    Var { name: "fertnitro_wwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2689 },
    Var { name: "fevpa", macros: &[], runtime: None, line: 549 },
    Var { name: "fevpg", macros: &[], runtime: None, line: 574 },
    Var { name: "fevpl", macros: &[], runtime: None, line: 559 },
    Var { name: "fgrnd", macros: &[], runtime: None, line: 579 },
    Var { name: "fh", macros: &[], runtime: None, line: 4612 },
    Var { name: "fhac", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 953 },
    Var { name: "fhah", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 968 },
    Var { name: "fldarea", macros: &[Cond::AnyOf(&["CatchLateralFlow"])], runtime: None, line: 670 },
    Var { name: "floodarea", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4800 },
    Var { name: "floodfrc", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4795 },
    Var { name: "fm", macros: &[], runtime: None, line: 4607 },
    Var { name: "fm10m", macros: &[], runtime: None, line: 4632 },
    Var { name: "fmeta", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 973 },
    Var { name: "fpg", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1302 },
    Var { name: "fpi", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1306 },
    Var { name: "fq", macros: &[], runtime: None, line: 4617 },
    Var { name: "frcsat", macros: &[], runtime: None, line: 751 },
    Var { name: "frootc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1083 },
    Var { name: "frootcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1592 },
    Var { name: "frootc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1088 },
    Var { name: "frootc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1597 },
    Var { name: "frootc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1093 },
    Var { name: "frootc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1603 },
    Var { name: "frootn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1192 },
    Var { name: "frootnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1692 },
    Var { name: "frootn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1197 },
    Var { name: "frootn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1697 },
    Var { name: "frootn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1202 },
    Var { name: "frootn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1703 },
    Var { name: "fsena", macros: &[], runtime: None, line: 539 },
    Var { name: "fseng", macros: &[], runtime: None, line: 569 },
    Var { name: "fsengimp", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 918 },
    Var { name: "fsengper", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 923 },
    Var { name: "fsenl", macros: &[], runtime: None, line: 554 },
    Var { name: "fsenroof", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 903 },
    Var { name: "fsenurbl", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 928 },
    Var { name: "fsenwsha", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 913 },
    Var { name: "fsenwsun", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 908 },
    Var { name: "fsno", macros: &[], runtime: None, line: 746 },
    Var { name: "fvehc", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 978 },
    Var { name: "fwst", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 958 },
    Var { name: "gddmaturity", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1388 },
    Var { name: "gddplant", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1393 },
    Var { name: "gdp", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_FIRE"), line: 1898 },
    Var { name: "gpp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1293 },
    Var { name: "gpp_c3arcgrass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2293 },
    Var { name: "gpp_c3grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2318 },
    Var { name: "gpp_c4grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2343 },
    Var { name: "gpp_dbfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2193 },
    Var { name: "gpp_dbftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2168 },
    Var { name: "gpp_dbftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2143 },
    Var { name: "gpp_dbsboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2268 },
    Var { name: "gpp_dbstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2243 },
    Var { name: "gpp_dnfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2068 },
    Var { name: "gpp_ebftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2118 },
    Var { name: "gpp_ebftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2093 },
    Var { name: "gpp_ebstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2218 },
    Var { name: "gpp_enfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2043 },
    Var { name: "gpp_enftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2018 },
    Var { name: "grainc", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1161 },
    Var { name: "grainc_storage", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1166 },
    Var { name: "grainc_to_cropprodc", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1424 },
    Var { name: "grainc_to_seed", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1429 },
    Var { name: "grainc_xfer", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1171 },
    Var { name: "grainn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1272 },
    Var { name: "grainn_storage", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1277 },
    Var { name: "grainn_xfer", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1282 },
    Var { name: "green", macros: &[], runtime: None, line: 761 },
    Var { name: "groundwater_demand", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1503 },
    Var { name: "groundwater_supply", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1513 },
    Var { name: "gssha", macros: &[], runtime: None, line: 1057 },
    Var { name: "gssun", macros: &[], runtime: None, line: 1052 },
    Var { name: "h2osoi", macros: &[], runtime: None, line: 4427 },
    Var { name: "hdm", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_FIRE"), line: 1906 },
    Var { name: "hr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1356 },
    Var { name: "hui", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1383 },
    Var { name: "huiswheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2421 },
    Var { name: "irrig_method_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 2835 },
    Var { name: "irrig_method_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2932 },
    Var { name: "irrig_method_rice1", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2956 },
    Var { name: "irrig_method_rice2", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2980 },
    Var { name: "irrig_method_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2908 },
    Var { name: "irrig_method_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3004 },
    Var { name: "irrig_method_swheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 2859 },
    Var { name: "irrig_method_wwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 2883 },
    Var { name: "lai", macros: &[], runtime: None, line: 766 },
    Var { name: "lai_c3arcgrass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2303 },
    Var { name: "lai_c3grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2328 },
    Var { name: "lai_c4grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2353 },
    Var { name: "lai_dbfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2203 },
    Var { name: "lai_dbftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2178 },
    Var { name: "lai_dbftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2153 },
    Var { name: "lai_dbsboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2278 },
    Var { name: "lai_dbstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2253 },
    Var { name: "lai_dnfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2078 },
    Var { name: "lai_ebftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2128 },
    Var { name: "lai_ebftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2103 },
    Var { name: "lai_ebstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2228 },
    Var { name: "lai_enfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2053 },
    Var { name: "lai_enftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2028 },
    Var { name: "laisha", macros: &[], runtime: None, line: 776 },
    Var { name: "laisun", macros: &[], runtime: None, line: 771 },
    Var { name: "lake_deficit", macros: &[], runtime: Some(".not. DEF_USE_Dynamic_Lake"), line: 4547 },
    Var { name: "lake_icefrac", macros: &[], runtime: None, line: 4541 },
    Var { name: "ldew", macros: &[], runtime: None, line: 731 },
    Var { name: "leafc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1068 },
    Var { name: "leafcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1576 },
    Var { name: "leafc_c3arcgrass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2298 },
    Var { name: "leafc_c3grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2323 },
    Var { name: "leafc_c4grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2348 },
    Var { name: "leafc_dbfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2198 },
    Var { name: "leafc_dbftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2173 },
    Var { name: "leafc_dbftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2148 },
    Var { name: "leafc_dbsboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2273 },
    Var { name: "leafc_dbstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2248 },
    Var { name: "leafc_dnfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2073 },
    Var { name: "leafc_ebftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2123 },
    Var { name: "leafc_ebftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2098 },
    Var { name: "leafc_ebstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2223 },
    Var { name: "leafc_enfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2048 },
    Var { name: "leafc_enftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2023 },
    Var { name: "leafc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1073 },
    Var { name: "leafc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1581 },
    Var { name: "leafc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1078 },
    Var { name: "leafc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1587 },
    Var { name: "leafn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1177 },
    Var { name: "leafnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1676 },
    Var { name: "leafn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1182 },
    Var { name: "leafn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1681 },
    Var { name: "leafn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1187 },
    Var { name: "leafn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1687 },
    Var { name: "lfevpa", macros: &[], runtime: None, line: 544 },
    Var { name: "lfevpgimp", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 938 },
    Var { name: "lfevpgper", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 943 },
    Var { name: "lfevproof", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 933 },
    Var { name: "lfevpurbl", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 948 },
    Var { name: "litr1cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1917 },
    Var { name: "litr1c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1785 },
    Var { name: "litr1nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1952 },
    Var { name: "litr1n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1820 },
    Var { name: "litr2cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1922 },
    Var { name: "litr2c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1790 },
    Var { name: "litr2nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1957 },
    Var { name: "litr2n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1825 },
    Var { name: "litr3cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1927 },
    Var { name: "litr3c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1795 },
    Var { name: "litr3nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1962 },
    Var { name: "litr3n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1830 },
    Var { name: "livecrootc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1128 },
    Var { name: "livecrootcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1642 },
    Var { name: "livecrootc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1133 },
    Var { name: "livecrootc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1647 },
    Var { name: "livecrootc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1139 },
    Var { name: "livecrootc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1653 },
    Var { name: "livecrootn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1239 },
    Var { name: "livecrootnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1742 },
    Var { name: "livecrootn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1244 },
    Var { name: "livecrootn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1747 },
    Var { name: "livecrootn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1250 },
    Var { name: "livecrootn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1753 },
    Var { name: "livestemc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1098 },
    Var { name: "livestemcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1608 },
    Var { name: "livestemc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1103 },
    Var { name: "livestemc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1613 },
    Var { name: "livestemc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1108 },
    Var { name: "livestemc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1619 },
    Var { name: "livestemn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1207 },
    Var { name: "livestemnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1708 },
    Var { name: "livestemn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1212 },
    Var { name: "livestemn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1713 },
    Var { name: "livestemn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1218 },
    Var { name: "livestemn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1719 },
    Var { name: "lnfm", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_FIRE"), line: 1910 },
    Var { name: "manunitro", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2391 },
    Var { name: "ndep_to_sminn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1570 },
    Var { name: "npp_c3arcgrass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2308 },
    Var { name: "npp_c3grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2333 },
    Var { name: "npp_c4grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2358 },
    Var { name: "npp_dbfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2208 },
    Var { name: "npp_dbftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2183 },
    Var { name: "npp_dbftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2158 },
    Var { name: "npp_dbsboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2283 },
    Var { name: "npp_dbstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2258 },
    Var { name: "npp_dnfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2083 },
    Var { name: "npp_ebftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2133 },
    Var { name: "npp_ebftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2108 },
    Var { name: "npp_ebstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2233 },
    Var { name: "npp_enfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2058 },
    Var { name: "npp_enftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2033 },
    Var { name: "npptoleafc_c3arcgrass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2313 },
    Var { name: "npptoleafc_c3grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2338 },
    Var { name: "npptoleafc_c4grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2363 },
    Var { name: "npptoleafc_dbfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2213 },
    Var { name: "npptoleafc_dbftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2188 },
    Var { name: "npptoleafc_dbftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2163 },
    Var { name: "npptoleafc_dbsboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2288 },
    Var { name: "npptoleafc_dbstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2263 },
    Var { name: "npptoleafc_dnfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2088 },
    Var { name: "npptoleafc_ebftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2138 },
    Var { name: "npptoleafc_ebftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2113 },
    Var { name: "npptoleafc_ebstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2238 },
    Var { name: "npptoleafc_enfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2063 },
    Var { name: "npptoleafc_enftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2038 },
    Var { name: "o3uptakesha", macros: &[], runtime: Some("DEF_USE_OZONESTRESS"), line: 503 },
    Var { name: "o3uptakesun", macros: &[], runtime: Some("DEF_USE_OZONESTRESS"), line: 499 },
    Var { name: "olrg", macros: &[], runtime: None, line: 599 },
    Var { name: "peatf", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_FIRE"), line: 1902 },
    Var { name: "plantdate_irrigated_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3310 },
    Var { name: "plantdate_irrigated_rice", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3370 },
    Var { name: "plantdate_irrigated_spwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3128 },
    Var { name: "plantdate_irrigated_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3430 },
    Var { name: "plantdate_irrigated_temp_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3066 },
    Var { name: "plantdate_irrigated_temp_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3249 },
    Var { name: "plantdate_irrigated_trop_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3490 },
    Var { name: "plantdate_irrigated_trop_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3551 },
    Var { name: "plantdate_irrigated_wtwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3188 },
    Var { name: "plantdate_rainfed_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3280 },
    Var { name: "plantdate_rainfed_rice", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3340 },
    Var { name: "plantdate_rainfed_spwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3097 },
    Var { name: "plantdate_rainfed_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3400 },
    Var { name: "plantdate_rainfed_temp_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3036 },
    Var { name: "plantdate_rainfed_temp_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3218 },
    Var { name: "plantdate_rainfed_trop_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3460 },
    Var { name: "plantdate_rainfed_trop_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3520 },
    Var { name: "plantdate_rainfed_wtwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3158 },
    Var { name: "plantdate_unmanagedcrop", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3583 },
    Var { name: "qcharge", macros: &[], runtime: Some("(.not.DEF_USE_VariablySaturatedFlow)"), line: 715 },
    Var { name: "qdrip", macros: &[], runtime: None, line: 686 },
    Var { name: "qinfl", macros: &[], runtime: None, line: 681 },
    Var { name: "qintr", macros: &[], runtime: None, line: 676 },
    Var { name: "qlayer", macros: &[], runtime: Some("DEF_USE_VariablySaturatedFlow"), line: 4433 },
    Var { name: "qref", macros: &[], runtime: None, line: 819 },
    Var { name: "qstar", macros: &[], runtime: None, line: 4592 },
    Var { name: "reservoir_supply", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1543 },
    Var { name: "reservoirriver_demand", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1523 },
    Var { name: "reservoirriver_supply", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1533 },
    Var { name: "respc", macros: &[], runtime: None, line: 710 },
    Var { name: "retrasn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1288 },
    Var { name: "rib", macros: &[], runtime: None, line: 4602 },
    Var { name: "river_supply", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1553 },
    Var { name: "rnet", macros: &[], runtime: None, line: 604 },
    Var { name: "rnof", macros: &[], runtime: None, line: 641 },
    Var { name: "rootr", macros: &[], runtime: None, line: 4441 },
    Var { name: "rss", macros: &[], runtime: None, line: 1062 },
    Var { name: "rstfacsha", macros: &[], runtime: None, line: 1047 },
    Var { name: "rstfacsun", macros: &[], runtime: None, line: 1042 },
    Var { name: "rsub", macros: &[], runtime: None, line: 636 },
    Var { name: "rsur", macros: &[], runtime: None, line: 619 },
    Var { name: "rsur_ie", macros: &[Cond::Not("CatchLateralFlow")], runtime: None, line: 630 },
    Var { name: "rsur_se", macros: &[Cond::Not("CatchLateralFlow")], runtime: None, line: 625 },
    Var { name: "runoff_supply", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1563 },
    Var { name: "sabg", macros: &[], runtime: None, line: 594 },
    Var { name: "sabvsha", macros: &[], runtime: None, line: 589 },
    Var { name: "sabvsun", macros: &[], runtime: None, line: 584 },
    Var { name: "sai", macros: &[], runtime: None, line: 781 },
    Var { name: "scv", macros: &[], runtime: None, line: 736 },
    Var { name: "sensors", macros: &[], runtime: None, line: 4744 },
    Var { name: "sigf", macros: &[], runtime: None, line: 756 },
    Var { name: "slope_factor_k", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_TWS_GRACE"), line: 652 },
    Var { name: "sminn_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1855 },
    Var { name: "snowdp", macros: &[], runtime: None, line: 741 },
    Var { name: "soil1cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1932 },
    Var { name: "soil1c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1800 },
    Var { name: "soil1nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1967 },
    Var { name: "soil1n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1835 },
    Var { name: "soil2cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1937 },
    Var { name: "soil2c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1805 },
    Var { name: "soil2nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1972 },
    Var { name: "soil2n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1840 },
    Var { name: "soil3cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1942 },
    Var { name: "soil3c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1810 },
    Var { name: "soil3nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1977 },
    Var { name: "soil3n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1845 },
    Var { name: "solnd", macros: &[], runtime: None, line: 4652 },
    Var { name: "solndln", macros: &[], runtime: None, line: 4706 },
    Var { name: "solni", macros: &[], runtime: None, line: 4657 },
    Var { name: "solniln", macros: &[], runtime: None, line: 4711 },
    Var { name: "solvd", macros: &[], runtime: None, line: 4642 },
    Var { name: "solvdln", macros: &[], runtime: None, line: 4696 },
    Var { name: "solvi", macros: &[], runtime: None, line: 4647 },
    Var { name: "solviln", macros: &[], runtime: None, line: 4701 },
    Var { name: "sr", macros: &[], runtime: None, line: 4637 },
    Var { name: "srnd", macros: &[], runtime: None, line: 4672 },
    Var { name: "srndln", macros: &[], runtime: None, line: 4726 },
    Var { name: "srni", macros: &[], runtime: None, line: 4677 },
    Var { name: "srniln", macros: &[], runtime: None, line: 4731 },
    Var { name: "srvd", macros: &[], runtime: None, line: 4662 },
    Var { name: "srvdln", macros: &[], runtime: None, line: 4716 },
    Var { name: "srvi", macros: &[], runtime: None, line: 4667 },
    Var { name: "srviln", macros: &[], runtime: None, line: 4721 },
    Var { name: "sum_deficit_irrig", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1478 },
    Var { name: "sum_irrig", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1468 },
    Var { name: "sum_irrig_count", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1483 },
    Var { name: "t2m_wmo", macros: &[], runtime: Some("DEF_Output_2mWMO"), line: 813 },
    Var { name: "t_brt_fy3d", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_FY"), line: 4368 },
    Var { name: "t_brt_fy3d_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_FY"), line: 4371 },
    Var { name: "t_brt_fy3d_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_ENS_NUM > 1"), line: 4375 },
    Var { name: "t_brt_fy3d_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_FY"), line: 4379 },
    Var { name: "t_brt_smap", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_SMAP"), line: 4351 },
    Var { name: "t_brt_smap_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_SMAP"), line: 4354 },
    Var { name: "t_brt_smap_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_ENS_NUM > 1"), line: 4358 },
    Var { name: "t_brt_smap_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_SMAP"), line: 4362 },
    Var { name: "t_grnd", macros: &[], runtime: None, line: 721 },
    Var { name: "t_lake", macros: &[], runtime: None, line: 4536 },
    Var { name: "t_roof", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 993 },
    Var { name: "t_room", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 983 },
    Var { name: "t_scalar", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1988 },
    Var { name: "t_soisno", macros: &[], runtime: None, line: 4186 },
    Var { name: "t_soisno_5cm", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4295 },
    Var { name: "t_soisno_5cm_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4298 },
    Var { name: "t_soisno_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_ENS_NUM > 1"), line: 4307 },
    Var { name: "t_soisno_ens_5cm_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4316 },
    Var { name: "t_wall", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 998 },
    Var { name: "tafu", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 988 },
    Var { name: "taux", macros: &[], runtime: None, line: 529 },
    Var { name: "tauy", macros: &[], runtime: None, line: 534 },
    Var { name: "tleaf", macros: &[], runtime: None, line: 726 },
    Var { name: "totcolc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1326 },
    Var { name: "totcoln", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1346 },
    Var { name: "totcwdc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1322 },
    Var { name: "totcwdn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1342 },
    Var { name: "totlitc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1314 },
    Var { name: "totlitn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1334 },
    Var { name: "totsoiln_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1860 },
    Var { name: "totsomc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1318 },
    Var { name: "totsomn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1338 },
    Var { name: "totvegc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1310 },
    Var { name: "totvegn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1330 },
    Var { name: "trad", macros: &[], runtime: None, line: 802 },
    Var { name: "tref", macros: &[], runtime: None, line: 807 },
    Var { name: "tstar", macros: &[], runtime: None, line: 4587 },
    Var { name: "us10m", macros: &[], runtime: None, line: 4622 },
    Var { name: "ustar", macros: &[], runtime: None, line: 4577 },
    Var { name: "ustar2", macros: &[], runtime: None, line: 4582 },
    Var { name: "vegwp", macros: &[], runtime: Some("DEF_USE_PLANTHYDRAULICS"), line: 4447 },
    Var { name: "veloc_riv_regrid", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4781 },
    Var { name: "vf", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1398 },
    Var { name: "vs10m", macros: &[], runtime: None, line: 4627 },
    Var { name: "w_scalar", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1993 },
    Var { name: "wa", macros: &[], runtime: None, line: 4479 },
    Var { name: "wa_inst", macros: &[], runtime: None, line: 4488 },
    Var { name: "wat", macros: &[], runtime: None, line: 691 },
    Var { name: "wat_inst", macros: &[], runtime: None, line: 700 },
    Var { name: "waterstorage", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1493 },
    Var { name: "wdpth_ucat_regrid", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4777 },
    Var { name: "wdsrf", macros: &[], runtime: None, line: 4493 },
    Var { name: "wdsrf_inst", macros: &[], runtime: None, line: 4502 },
    Var { name: "wetwat", macros: &[], runtime: Some("DEF_USE_Dynamic_Wetland"), line: 852 },
    Var { name: "wetwat_inst", macros: &[], runtime: None, line: 866 },
    Var { name: "wetzwt", macros: &[], runtime: None, line: 873 },
    Var { name: "wfc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1871 },
    Var { name: "wice_soisno", macros: &[], runtime: None, line: 4198 },
    Var { name: "wliq_h2osoi_5cm", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4287 },
    Var { name: "wliq_h2osoi_5cm_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4290 },
    Var { name: "wliq_soisno", macros: &[], runtime: None, line: 4192 },
    Var { name: "wliq_soisno_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_ENS_NUM > 1"), line: 4304 },
    Var { name: "wliq_soisno_ens_5cm_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4313 },
    Var { name: "xerr", macros: &[], runtime: None, line: 609 },
    Var { name: "xwsub", macros: &[Cond::AnyOf(&["CatchLateralFlow"])], runtime: None, line: 665 },
    Var { name: "xwsur", macros: &[Cond::AnyOf(&["CatchLateralFlow"])], runtime: None, line: 660 },
    Var { name: "xy_frl", macros: &[], runtime: None, line: 472 },
    Var { name: "xy_hpbl", macros: &[], runtime: Some("DEF_USE_CBL_HEIGHT"), line: 493 },
    Var { name: "xy_ozone", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_OZONESTRESS"), line: 1779 },
    Var { name: "xy_pbot", macros: &[], runtime: None, line: 467 },
    Var { name: "xy_prc", macros: &[], runtime: None, line: 457 },
    Var { name: "xy_prl", macros: &[], runtime: None, line: 462 },
    Var { name: "xy_q", macros: &[], runtime: None, line: 452 },
    Var { name: "xy_rain", macros: &[], runtime: None, line: 482 },
    Var { name: "xy_snow", macros: &[], runtime: None, line: 487 },
    Var { name: "xy_solarin", macros: &[], runtime: None, line: 477 },
    Var { name: "xy_t", macros: &[], runtime: None, line: 447 },
    Var { name: "xy_us", macros: &[], runtime: None, line: 437 },
    Var { name: "xy_vs", macros: &[], runtime: None, line: 442 },
    Var { name: "z0m", macros: &[], runtime: None, line: 797 },
    Var { name: "zerr", macros: &[], runtime: None, line: 614 },
    Var { name: "zol", macros: &[], runtime: None, line: 4597 },
    Var { name: "zwt", macros: &[], runtime: None, line: 4454 },
];
