//! 由 `cargo run -p xtask -- gen-histmap` 生成。**不要手改。**
//!
//! 源：vendor/CoLM202X/main/MOD_Hist.F90
//! 漂移由 crates/colm-hist/tests/drift.rs 守住。

use crate::{Cond, Var};

// 一个变量一行 —— 上游改一处，diff 就只有一行。rustfmt 会把每条拆成
// 六行（456 条 -> 近三千行），那样 code review 里就看不出改了什么了。
// colm-schema 的同类文件不用写这条：它有一条 626 字符、断不开的数组
// 默认值，rustfmt 因此整块放弃 —— 那是巧合，不是设计，这里写明。
#[rustfmt::skip]
pub static VARS: &[Var] = &[
    Var { name: "BD_all", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1857 },
    Var { name: "CONC_O2_UNSAT", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_NITRIF"), line: 1873 },
    Var { name: "O2_DECOMP_DEPTH_UNSAT", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_NITRIF"), line: 1878 },
    Var { name: "OM_density", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1867 },
    Var { name: "abm", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_FIRE"), line: 1885 },
    Var { name: "alb", macros: &[], runtime: None, line: 777 },
    Var { name: "ar", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1342 },
    Var { name: "assim", macros: &[], runtime: None, line: 696 },
    Var { name: "assimsha", macros: &[], runtime: None, line: 1017 },
    Var { name: "assimsun", macros: &[], runtime: None, line: 1011 },
    Var { name: "cphase", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1363 },
    Var { name: "cropprod1c", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1394 },
    Var { name: "cropprod1c_loss", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1399 },
    Var { name: "cropprodc_irrigated_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3876 },
    Var { name: "cropprodc_irrigated_rice", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3936 },
    Var { name: "cropprodc_irrigated_spwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3694 },
    Var { name: "cropprodc_irrigated_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3996 },
    Var { name: "cropprodc_irrigated_temp_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3634 },
    Var { name: "cropprodc_irrigated_temp_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3815 },
    Var { name: "cropprodc_irrigated_trop_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4056 },
    Var { name: "cropprodc_irrigated_trop_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4117 },
    Var { name: "cropprodc_irrigated_wtwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3754 },
    Var { name: "cropprodc_rainfed_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3846 },
    Var { name: "cropprodc_rainfed_rice", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3906 },
    Var { name: "cropprodc_rainfed_spwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3664 },
    Var { name: "cropprodc_rainfed_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3966 },
    Var { name: "cropprodc_rainfed_temp_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3604 },
    Var { name: "cropprodc_rainfed_temp_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3784 },
    Var { name: "cropprodc_rainfed_trop_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4026 },
    Var { name: "cropprodc_rainfed_trop_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4086 },
    Var { name: "cropprodc_rainfed_wtwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3724 },
    Var { name: "cropprodc_unmanagedcrop", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 4148 },
    Var { name: "cropseedc_deficit", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1404 },
    Var { name: "cwdcCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1938 },
    Var { name: "cwdc_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1806 },
    Var { name: "cwdnCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1973 },
    Var { name: "cwdn_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1841 },
    Var { name: "deadcrootc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1135 },
    Var { name: "deadcrootcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1650 },
    Var { name: "deadcrootc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1140 },
    Var { name: "deadcrootc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1655 },
    Var { name: "deadcrootc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1146 },
    Var { name: "deadcrootc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1661 },
    Var { name: "deadcrootn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1246 },
    Var { name: "deadcrootnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1750 },
    Var { name: "deadcrootn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1251 },
    Var { name: "deadcrootn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1755 },
    Var { name: "deadcrootn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1257 },
    Var { name: "deadcrootn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1761 },
    Var { name: "deadstemc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1104 },
    Var { name: "deadstemcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1616 },
    Var { name: "deadstemc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1109 },
    Var { name: "deadstemc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1621 },
    Var { name: "deadstemc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1114 },
    Var { name: "deadstemc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1627 },
    Var { name: "deadstemn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1214 },
    Var { name: "deadstemnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1716 },
    Var { name: "deadstemn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1219 },
    Var { name: "deadstemn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1721 },
    Var { name: "deadstemn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1225 },
    Var { name: "deadstemn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1727 },
    Var { name: "discharge", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4776 },
    Var { name: "discharge_rivermouth_regrid", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4781 },
    Var { name: "downreg", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1289 },
    Var { name: "dz_lake", macros: &[], runtime: Some("DEF_USE_Dynamic_Lake"), line: 4522 },
    Var { name: "emis", macros: &[], runtime: None, line: 783 },
    Var { name: "etr", macros: &[], runtime: None, line: 555 },
    Var { name: "etrsha", macros: &[], runtime: None, line: 1028 },
    Var { name: "etrsun", macros: &[], runtime: None, line: 1023 },
    Var { name: "fach", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 954 },
    Var { name: "fert_to_sminn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1424 },
    Var { name: "fertnitro_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2632 },
    Var { name: "fertnitro_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2729 },
    Var { name: "fertnitro_rice1", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2753 },
    Var { name: "fertnitro_rice2", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2777 },
    Var { name: "fertnitro_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2705 },
    Var { name: "fertnitro_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2801 },
    Var { name: "fertnitro_swheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2656 },
    Var { name: "fertnitro_wwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2680 },
    Var { name: "fevpa", macros: &[], runtime: None, line: 540 },
    Var { name: "fevpg", macros: &[], runtime: None, line: 565 },
    Var { name: "fevpl", macros: &[], runtime: None, line: 550 },
    Var { name: "fgrnd", macros: &[], runtime: None, line: 570 },
    Var { name: "fh", macros: &[], runtime: None, line: 4603 },
    Var { name: "fhac", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 944 },
    Var { name: "fhah", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 959 },
    Var { name: "fldarea", macros: &[Cond::AnyOf(&["CatchLateralFlow"])], runtime: None, line: 661 },
    Var { name: "floodarea", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4791 },
    Var { name: "floodfrc", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4786 },
    Var { name: "fm", macros: &[], runtime: None, line: 4598 },
    Var { name: "fm10m", macros: &[], runtime: None, line: 4623 },
    Var { name: "fmeta", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 964 },
    Var { name: "fpg", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1293 },
    Var { name: "fpi", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1297 },
    Var { name: "fq", macros: &[], runtime: None, line: 4608 },
    Var { name: "frcsat", macros: &[], runtime: None, line: 742 },
    Var { name: "frootc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1074 },
    Var { name: "frootcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1583 },
    Var { name: "frootc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1079 },
    Var { name: "frootc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1588 },
    Var { name: "frootc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1084 },
    Var { name: "frootc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1594 },
    Var { name: "frootn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1183 },
    Var { name: "frootnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1683 },
    Var { name: "frootn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1188 },
    Var { name: "frootn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1688 },
    Var { name: "frootn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1193 },
    Var { name: "frootn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1694 },
    Var { name: "fsena", macros: &[], runtime: None, line: 530 },
    Var { name: "fseng", macros: &[], runtime: None, line: 560 },
    Var { name: "fsengimp", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 909 },
    Var { name: "fsengper", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 914 },
    Var { name: "fsenl", macros: &[], runtime: None, line: 545 },
    Var { name: "fsenroof", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 894 },
    Var { name: "fsenurbl", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 919 },
    Var { name: "fsenwsha", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 904 },
    Var { name: "fsenwsun", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 899 },
    Var { name: "fsno", macros: &[], runtime: None, line: 737 },
    Var { name: "fvehc", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 969 },
    Var { name: "fwst", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 949 },
    Var { name: "gddmaturity", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1379 },
    Var { name: "gddplant", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1384 },
    Var { name: "gdp", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_FIRE"), line: 1889 },
    Var { name: "gpp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1284 },
    Var { name: "gpp_c3arcgrass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2284 },
    Var { name: "gpp_c3grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2309 },
    Var { name: "gpp_c4grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2334 },
    Var { name: "gpp_dbfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2184 },
    Var { name: "gpp_dbftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2159 },
    Var { name: "gpp_dbftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2134 },
    Var { name: "gpp_dbsboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2259 },
    Var { name: "gpp_dbstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2234 },
    Var { name: "gpp_dnfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2059 },
    Var { name: "gpp_ebftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2109 },
    Var { name: "gpp_ebftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2084 },
    Var { name: "gpp_ebstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2209 },
    Var { name: "gpp_enfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2034 },
    Var { name: "gpp_enftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2009 },
    Var { name: "grainc", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1152 },
    Var { name: "grainc_storage", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1157 },
    Var { name: "grainc_to_cropprodc", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1415 },
    Var { name: "grainc_to_seed", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1420 },
    Var { name: "grainc_xfer", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1162 },
    Var { name: "grainn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1263 },
    Var { name: "grainn_storage", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1268 },
    Var { name: "grainn_xfer", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1273 },
    Var { name: "green", macros: &[], runtime: None, line: 752 },
    Var { name: "groundwater_demand", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1494 },
    Var { name: "groundwater_supply", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1504 },
    Var { name: "gssha", macros: &[], runtime: None, line: 1048 },
    Var { name: "gssun", macros: &[], runtime: None, line: 1043 },
    Var { name: "h2osoi", macros: &[], runtime: None, line: 4418 },
    Var { name: "hdm", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_FIRE"), line: 1897 },
    Var { name: "hr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1347 },
    Var { name: "hui", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1374 },
    Var { name: "huiswheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2412 },
    Var { name: "irrig_method_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 2826 },
    Var { name: "irrig_method_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2923 },
    Var { name: "irrig_method_rice1", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2947 },
    Var { name: "irrig_method_rice2", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2971 },
    Var { name: "irrig_method_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2899 },
    Var { name: "irrig_method_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2995 },
    Var { name: "irrig_method_swheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 2850 },
    Var { name: "irrig_method_wwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 2874 },
    Var { name: "lai", macros: &[], runtime: None, line: 757 },
    Var { name: "lai_c3arcgrass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2294 },
    Var { name: "lai_c3grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2319 },
    Var { name: "lai_c4grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2344 },
    Var { name: "lai_dbfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2194 },
    Var { name: "lai_dbftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2169 },
    Var { name: "lai_dbftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2144 },
    Var { name: "lai_dbsboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2269 },
    Var { name: "lai_dbstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2244 },
    Var { name: "lai_dnfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2069 },
    Var { name: "lai_ebftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2119 },
    Var { name: "lai_ebftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2094 },
    Var { name: "lai_ebstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2219 },
    Var { name: "lai_enfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2044 },
    Var { name: "lai_enftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2019 },
    Var { name: "laisha", macros: &[], runtime: None, line: 767 },
    Var { name: "laisun", macros: &[], runtime: None, line: 762 },
    Var { name: "lake_deficit", macros: &[], runtime: Some(".not. DEF_USE_Dynamic_Lake"), line: 4538 },
    Var { name: "lake_icefrac", macros: &[], runtime: None, line: 4532 },
    Var { name: "ldew", macros: &[], runtime: None, line: 722 },
    Var { name: "leafc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1059 },
    Var { name: "leafcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1567 },
    Var { name: "leafc_c3arcgrass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2289 },
    Var { name: "leafc_c3grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2314 },
    Var { name: "leafc_c4grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2339 },
    Var { name: "leafc_dbfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2189 },
    Var { name: "leafc_dbftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2164 },
    Var { name: "leafc_dbftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2139 },
    Var { name: "leafc_dbsboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2264 },
    Var { name: "leafc_dbstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2239 },
    Var { name: "leafc_dnfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2064 },
    Var { name: "leafc_ebftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2114 },
    Var { name: "leafc_ebftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2089 },
    Var { name: "leafc_ebstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2214 },
    Var { name: "leafc_enfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2039 },
    Var { name: "leafc_enftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2014 },
    Var { name: "leafc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1064 },
    Var { name: "leafc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1572 },
    Var { name: "leafc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1069 },
    Var { name: "leafc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1578 },
    Var { name: "leafn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1168 },
    Var { name: "leafnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1667 },
    Var { name: "leafn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1173 },
    Var { name: "leafn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1672 },
    Var { name: "leafn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1178 },
    Var { name: "leafn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1678 },
    Var { name: "lfevpa", macros: &[], runtime: None, line: 535 },
    Var { name: "lfevpgimp", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 929 },
    Var { name: "lfevpgper", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 934 },
    Var { name: "lfevproof", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 924 },
    Var { name: "lfevpurbl", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 939 },
    Var { name: "litr1cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1908 },
    Var { name: "litr1c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1776 },
    Var { name: "litr1nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1943 },
    Var { name: "litr1n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1811 },
    Var { name: "litr2cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1913 },
    Var { name: "litr2c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1781 },
    Var { name: "litr2nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1948 },
    Var { name: "litr2n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1816 },
    Var { name: "litr3cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1918 },
    Var { name: "litr3c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1786 },
    Var { name: "litr3nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1953 },
    Var { name: "litr3n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1821 },
    Var { name: "livecrootc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1119 },
    Var { name: "livecrootcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1633 },
    Var { name: "livecrootc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1124 },
    Var { name: "livecrootc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1638 },
    Var { name: "livecrootc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1130 },
    Var { name: "livecrootc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1644 },
    Var { name: "livecrootn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1230 },
    Var { name: "livecrootnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1733 },
    Var { name: "livecrootn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1235 },
    Var { name: "livecrootn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1738 },
    Var { name: "livecrootn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1241 },
    Var { name: "livecrootn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1744 },
    Var { name: "livestemc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1089 },
    Var { name: "livestemcCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1599 },
    Var { name: "livestemc_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1094 },
    Var { name: "livestemc_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1604 },
    Var { name: "livestemc_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1099 },
    Var { name: "livestemc_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1610 },
    Var { name: "livestemn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1198 },
    Var { name: "livestemnCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1699 },
    Var { name: "livestemn_storage", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1203 },
    Var { name: "livestemn_storageCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1704 },
    Var { name: "livestemn_xfer", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1209 },
    Var { name: "livestemn_xferCap", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1710 },
    Var { name: "lnfm", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_FIRE"), line: 1901 },
    Var { name: "manunitro", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 2382 },
    Var { name: "ndep_to_sminn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1561 },
    Var { name: "npp_c3arcgrass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2299 },
    Var { name: "npp_c3grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2324 },
    Var { name: "npp_c4grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2349 },
    Var { name: "npp_dbfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2199 },
    Var { name: "npp_dbftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2174 },
    Var { name: "npp_dbftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2149 },
    Var { name: "npp_dbsboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2274 },
    Var { name: "npp_dbstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2249 },
    Var { name: "npp_dnfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2074 },
    Var { name: "npp_ebftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2124 },
    Var { name: "npp_ebftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2099 },
    Var { name: "npp_ebstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2224 },
    Var { name: "npp_enfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2049 },
    Var { name: "npp_enftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2024 },
    Var { name: "npptoleafc_c3arcgrass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2304 },
    Var { name: "npptoleafc_c3grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2329 },
    Var { name: "npptoleafc_c4grass", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2354 },
    Var { name: "npptoleafc_dbfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2204 },
    Var { name: "npptoleafc_dbftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2179 },
    Var { name: "npptoleafc_dbftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2154 },
    Var { name: "npptoleafc_dbsboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2279 },
    Var { name: "npptoleafc_dbstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2254 },
    Var { name: "npptoleafc_dnfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2079 },
    Var { name: "npptoleafc_ebftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2129 },
    Var { name: "npptoleafc_ebftrop", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2104 },
    Var { name: "npptoleafc_ebstemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2229 },
    Var { name: "npptoleafc_enfboreal", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2054 },
    Var { name: "npptoleafc_enftemp", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 2029 },
    Var { name: "o3uptakesha", macros: &[], runtime: Some("DEF_USE_OZONESTRESS"), line: 494 },
    Var { name: "o3uptakesun", macros: &[], runtime: Some("DEF_USE_OZONESTRESS"), line: 490 },
    Var { name: "olrg", macros: &[], runtime: None, line: 590 },
    Var { name: "peatf", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_FIRE"), line: 1893 },
    Var { name: "plantdate_irrigated_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3301 },
    Var { name: "plantdate_irrigated_rice", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3361 },
    Var { name: "plantdate_irrigated_spwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3119 },
    Var { name: "plantdate_irrigated_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3421 },
    Var { name: "plantdate_irrigated_temp_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3057 },
    Var { name: "plantdate_irrigated_temp_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3240 },
    Var { name: "plantdate_irrigated_trop_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3481 },
    Var { name: "plantdate_irrigated_trop_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3542 },
    Var { name: "plantdate_irrigated_wtwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3179 },
    Var { name: "plantdate_rainfed_cotton", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3271 },
    Var { name: "plantdate_rainfed_rice", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3331 },
    Var { name: "plantdate_rainfed_spwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3088 },
    Var { name: "plantdate_rainfed_sugarcane", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3391 },
    Var { name: "plantdate_rainfed_temp_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3027 },
    Var { name: "plantdate_rainfed_temp_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3209 },
    Var { name: "plantdate_rainfed_trop_corn", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3451 },
    Var { name: "plantdate_rainfed_trop_soybean", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3511 },
    Var { name: "plantdate_rainfed_wtwheat", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3149 },
    Var { name: "plantdate_unmanagedcrop", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 3574 },
    Var { name: "qcharge", macros: &[], runtime: Some("(.not.DEF_USE_VariablySaturatedFlow)"), line: 706 },
    Var { name: "qdrip", macros: &[], runtime: None, line: 677 },
    Var { name: "qinfl", macros: &[], runtime: None, line: 672 },
    Var { name: "qintr", macros: &[], runtime: None, line: 667 },
    Var { name: "qlayer", macros: &[], runtime: Some("DEF_USE_VariablySaturatedFlow"), line: 4424 },
    Var { name: "qref", macros: &[], runtime: None, line: 810 },
    Var { name: "qstar", macros: &[], runtime: None, line: 4583 },
    Var { name: "reservoir_supply", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1534 },
    Var { name: "reservoirriver_demand", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1514 },
    Var { name: "reservoirriver_supply", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1524 },
    Var { name: "respc", macros: &[], runtime: None, line: 701 },
    Var { name: "retrasn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1279 },
    Var { name: "rib", macros: &[], runtime: None, line: 4593 },
    Var { name: "river_supply", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1544 },
    Var { name: "rnet", macros: &[], runtime: None, line: 595 },
    Var { name: "rnof", macros: &[], runtime: None, line: 632 },
    Var { name: "rootr", macros: &[], runtime: None, line: 4432 },
    Var { name: "rss", macros: &[], runtime: None, line: 1053 },
    Var { name: "rstfacsha", macros: &[], runtime: None, line: 1038 },
    Var { name: "rstfacsun", macros: &[], runtime: None, line: 1033 },
    Var { name: "rsub", macros: &[], runtime: None, line: 627 },
    Var { name: "rsur", macros: &[], runtime: None, line: 610 },
    Var { name: "rsur_ie", macros: &[Cond::Not("CatchLateralFlow")], runtime: None, line: 621 },
    Var { name: "rsur_se", macros: &[Cond::Not("CatchLateralFlow")], runtime: None, line: 616 },
    Var { name: "runoff_supply", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1554 },
    Var { name: "sabg", macros: &[], runtime: None, line: 585 },
    Var { name: "sabvsha", macros: &[], runtime: None, line: 580 },
    Var { name: "sabvsun", macros: &[], runtime: None, line: 575 },
    Var { name: "sai", macros: &[], runtime: None, line: 772 },
    Var { name: "scv", macros: &[], runtime: None, line: 727 },
    Var { name: "sensors", macros: &[], runtime: None, line: 4735 },
    Var { name: "sigf", macros: &[], runtime: None, line: 747 },
    Var { name: "slope_factor_k", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_TWS_GRACE"), line: 643 },
    Var { name: "sminn_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1846 },
    Var { name: "snowdp", macros: &[], runtime: None, line: 732 },
    Var { name: "soil1cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1923 },
    Var { name: "soil1c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1791 },
    Var { name: "soil1nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1958 },
    Var { name: "soil1n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1826 },
    Var { name: "soil2cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1928 },
    Var { name: "soil2c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1796 },
    Var { name: "soil2nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1963 },
    Var { name: "soil2n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1831 },
    Var { name: "soil3cCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1933 },
    Var { name: "soil3c_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1801 },
    Var { name: "soil3nCap_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1968 },
    Var { name: "soil3n_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1836 },
    Var { name: "solnd", macros: &[], runtime: None, line: 4643 },
    Var { name: "solndln", macros: &[], runtime: None, line: 4697 },
    Var { name: "solni", macros: &[], runtime: None, line: 4648 },
    Var { name: "solniln", macros: &[], runtime: None, line: 4702 },
    Var { name: "solvd", macros: &[], runtime: None, line: 4633 },
    Var { name: "solvdln", macros: &[], runtime: None, line: 4687 },
    Var { name: "solvi", macros: &[], runtime: None, line: 4638 },
    Var { name: "solviln", macros: &[], runtime: None, line: 4692 },
    Var { name: "sr", macros: &[], runtime: None, line: 4628 },
    Var { name: "srnd", macros: &[], runtime: None, line: 4663 },
    Var { name: "srndln", macros: &[], runtime: None, line: 4717 },
    Var { name: "srni", macros: &[], runtime: None, line: 4668 },
    Var { name: "srniln", macros: &[], runtime: None, line: 4722 },
    Var { name: "srvd", macros: &[], runtime: None, line: 4653 },
    Var { name: "srvdln", macros: &[], runtime: None, line: 4707 },
    Var { name: "srvi", macros: &[], runtime: None, line: 4658 },
    Var { name: "srviln", macros: &[], runtime: None, line: 4712 },
    Var { name: "sum_deficit_irrig", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1469 },
    Var { name: "sum_irrig", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1459 },
    Var { name: "sum_irrig_count", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1474 },
    Var { name: "t2m_wmo", macros: &[], runtime: Some("DEF_Output_2mWMO"), line: 804 },
    Var { name: "t_brt_fy3d", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_FY"), line: 4359 },
    Var { name: "t_brt_fy3d_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_FY"), line: 4362 },
    Var { name: "t_brt_fy3d_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_ENS_NUM > 1"), line: 4366 },
    Var { name: "t_brt_fy3d_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_FY"), line: 4370 },
    Var { name: "t_brt_smap", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_SMAP"), line: 4342 },
    Var { name: "t_brt_smap_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_SMAP"), line: 4345 },
    Var { name: "t_brt_smap_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_ENS_NUM > 1"), line: 4349 },
    Var { name: "t_brt_smap_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_SMAP"), line: 4353 },
    Var { name: "t_grnd", macros: &[], runtime: None, line: 712 },
    Var { name: "t_lake", macros: &[], runtime: None, line: 4527 },
    Var { name: "t_roof", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 984 },
    Var { name: "t_room", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 974 },
    Var { name: "t_scalar", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1979 },
    Var { name: "t_soisno", macros: &[], runtime: None, line: 4177 },
    Var { name: "t_soisno_5cm", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4286 },
    Var { name: "t_soisno_5cm_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4289 },
    Var { name: "t_soisno_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_ENS_NUM > 1"), line: 4298 },
    Var { name: "t_soisno_ens_5cm_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4307 },
    Var { name: "t_wall", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 989 },
    Var { name: "tafu", macros: &[Cond::AnyOf(&["URBAN_MODEL"])], runtime: None, line: 979 },
    Var { name: "taux", macros: &[], runtime: None, line: 520 },
    Var { name: "tauy", macros: &[], runtime: None, line: 525 },
    Var { name: "tleaf", macros: &[], runtime: None, line: 717 },
    Var { name: "totcolc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1317 },
    Var { name: "totcoln", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1337 },
    Var { name: "totcwdc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1313 },
    Var { name: "totcwdn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1333 },
    Var { name: "totlitc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1305 },
    Var { name: "totlitn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1325 },
    Var { name: "totsoiln_vr", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1851 },
    Var { name: "totsomc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1309 },
    Var { name: "totsomn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1329 },
    Var { name: "totvegc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1301 },
    Var { name: "totvegn", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1321 },
    Var { name: "trad", macros: &[], runtime: None, line: 793 },
    Var { name: "tref", macros: &[], runtime: None, line: 798 },
    Var { name: "tstar", macros: &[], runtime: None, line: 4578 },
    Var { name: "us10m", macros: &[], runtime: None, line: 4613 },
    Var { name: "ustar", macros: &[], runtime: None, line: 4568 },
    Var { name: "ustar2", macros: &[], runtime: None, line: 4573 },
    Var { name: "vegwp", macros: &[], runtime: Some("DEF_USE_PLANTHYDRAULICS"), line: 4438 },
    Var { name: "veloc_riv_regrid", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4772 },
    Var { name: "vf", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: None, line: 1389 },
    Var { name: "vs10m", macros: &[], runtime: None, line: 4618 },
    Var { name: "w_scalar", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_DiagMatrix"), line: 1984 },
    Var { name: "wa", macros: &[], runtime: None, line: 4470 },
    Var { name: "wa_inst", macros: &[], runtime: None, line: 4479 },
    Var { name: "wat", macros: &[], runtime: None, line: 682 },
    Var { name: "wat_inst", macros: &[], runtime: None, line: 691 },
    Var { name: "waterstorage", macros: &[Cond::AnyOf(&["BGC"]), Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_IRRIGATION"), line: 1484 },
    Var { name: "wdpth_ucat_regrid", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4768 },
    Var { name: "wdsrf", macros: &[], runtime: None, line: 4484 },
    Var { name: "wdsrf_inst", macros: &[], runtime: None, line: 4493 },
    Var { name: "wetwat", macros: &[], runtime: Some("DEF_USE_Dynamic_Wetland"), line: 843 },
    Var { name: "wetwat_inst", macros: &[], runtime: None, line: 857 },
    Var { name: "wetzwt", macros: &[], runtime: None, line: 864 },
    Var { name: "wfc", macros: &[Cond::AnyOf(&["BGC"])], runtime: None, line: 1862 },
    Var { name: "wice_soisno", macros: &[], runtime: None, line: 4189 },
    Var { name: "wliq_h2osoi_5cm", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4278 },
    Var { name: "wliq_h2osoi_5cm_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4281 },
    Var { name: "wliq_soisno", macros: &[], runtime: None, line: 4183 },
    Var { name: "wliq_soisno_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_ENS_NUM > 1"), line: 4295 },
    Var { name: "wliq_soisno_ens_5cm_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4304 },
    Var { name: "xerr", macros: &[], runtime: None, line: 600 },
    Var { name: "xwsub", macros: &[Cond::AnyOf(&["CatchLateralFlow"])], runtime: None, line: 656 },
    Var { name: "xwsur", macros: &[Cond::AnyOf(&["CatchLateralFlow"])], runtime: None, line: 651 },
    Var { name: "xy_frl", macros: &[], runtime: None, line: 463 },
    Var { name: "xy_hpbl", macros: &[], runtime: Some("DEF_USE_CBL_HEIGHT"), line: 484 },
    Var { name: "xy_ozone", macros: &[Cond::AnyOf(&["BGC"])], runtime: Some("DEF_USE_OZONESTRESS"), line: 1770 },
    Var { name: "xy_pbot", macros: &[], runtime: None, line: 458 },
    Var { name: "xy_prc", macros: &[], runtime: None, line: 448 },
    Var { name: "xy_prl", macros: &[], runtime: None, line: 453 },
    Var { name: "xy_q", macros: &[], runtime: None, line: 443 },
    Var { name: "xy_rain", macros: &[], runtime: None, line: 473 },
    Var { name: "xy_snow", macros: &[], runtime: None, line: 478 },
    Var { name: "xy_solarin", macros: &[], runtime: None, line: 468 },
    Var { name: "xy_t", macros: &[], runtime: None, line: 438 },
    Var { name: "xy_us", macros: &[], runtime: None, line: 428 },
    Var { name: "xy_vs", macros: &[], runtime: None, line: 433 },
    Var { name: "z0m", macros: &[], runtime: None, line: 788 },
    Var { name: "zerr", macros: &[], runtime: None, line: 605 },
    Var { name: "zol", macros: &[], runtime: None, line: 4588 },
    Var { name: "zwt", macros: &[], runtime: None, line: 4445 },
];
