//! 由 `cargo run -p xtask -- gen-histmap` 生成。**不要手改。**
//!
//! 源：vendor/CoLM202X/main/MOD_Hist.F90
//!     vendor/CoLM202X/main/TRACER/MOD_Tracer_Reactive_Methane_Hist.F90
//! 漂移由 crates/colm-hist/tests/drift.rs 守住。

use crate::{Cond, Var};

// 一个变量一行 —— 上游改一处，diff 就只有一行。rustfmt 会把每条拆成
// 六行（618 条 -> 近四千行），那样 code review 里就看不出改了什么了。
// colm-schema 的同类文件不用写这条：它有一条 626 字符、断不开的数组
// 默认值，rustfmt 因此整块放弃 —— 那是巧合，不是设计，这里写明。
#[rustfmt::skip]
pub static VARS: &[Var] = &[
    Var { name: "BD_all", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1849 },
    Var { name: "CONC_O2_UNSAT", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_NITRIF)"), line: 1865 },
    Var { name: "O2_DECOMP_DEPTH_UNSAT", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_NITRIF)"), line: 1870 },
    Var { name: "OM_density", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1859 },
    Var { name: "abm", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_FIRE)"), line: 1877 },
    Var { name: "alb", macros: &[], runtime: None, line: 769 },
    Var { name: "annavg_agnpp", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1046 },
    Var { name: "annavg_bgnpp", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1050 },
    Var { name: "annavg_finrw", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1058 },
    Var { name: "annavg_somhr", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1054 },
    Var { name: "ar", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1334 },
    Var { name: "assim", macros: &[], runtime: None, line: 688 },
    Var { name: "assimsha", macros: &[], runtime: None, line: 1009 },
    Var { name: "assimsun", macros: &[], runtime: None, line: 1003 },
    Var { name: "co2_aere_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 383 },
    Var { name: "co2_aere_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 695 },
    Var { name: "co2_aere_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 691 },
    Var { name: "co2_aere_tot", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 502 },
    Var { name: "co2_decomp_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 355 },
    Var { name: "co2_decomp_depth_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 922 },
    Var { name: "co2_decomp_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 679 },
    Var { name: "co2_decomp_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 675 },
    Var { name: "co2_decomp_tot", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 494 },
    Var { name: "co2_decomp_tot_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 970 },
    Var { name: "co2_decomp_tot_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 703 },
    Var { name: "co2_decomp_tot_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 699 },
    Var { name: "co2_net_tot", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 506 },
    Var { name: "co2_net_tot_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 978 },
    Var { name: "co2_net_tot_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 719 },
    Var { name: "co2_net_tot_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 715 },
    Var { name: "co2_oxid_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 367 },
    Var { name: "co2_oxid_depth_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 926 },
    Var { name: "co2_oxid_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 687 },
    Var { name: "co2_oxid_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 683 },
    Var { name: "co2_oxid_tot", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 498 },
    Var { name: "co2_oxid_tot_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 974 },
    Var { name: "co2_oxid_tot_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 711 },
    Var { name: "co2_oxid_tot_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 707 },
    Var { name: "conc_methane", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 522 },
    Var { name: "conc_methane_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 994 },
    Var { name: "conc_methane_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 808 },
    Var { name: "conc_methane_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 804 },
    Var { name: "conc_o2", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 518 },
    Var { name: "conc_o2_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 990 },
    Var { name: "conc_o2_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 800 },
    Var { name: "conc_o2_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 796 },
    Var { name: "cphase", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1355 },
    Var { name: "cropprod1c", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1386 },
    Var { name: "cropprod1c_loss", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1391 },
    Var { name: "cropprodc_irrigated_cotton", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3812 },
    Var { name: "cropprodc_irrigated_rice", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3872 },
    Var { name: "cropprodc_irrigated_spwheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3630 },
    Var { name: "cropprodc_irrigated_sugarcane", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3932 },
    Var { name: "cropprodc_irrigated_temp_corn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3570 },
    Var { name: "cropprodc_irrigated_temp_soybean", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3751 },
    Var { name: "cropprodc_irrigated_trop_corn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3992 },
    Var { name: "cropprodc_irrigated_trop_soybean", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 4053 },
    Var { name: "cropprodc_irrigated_wtwheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3690 },
    Var { name: "cropprodc_rainfed_cotton", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3782 },
    Var { name: "cropprodc_rainfed_rice", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3842 },
    Var { name: "cropprodc_rainfed_spwheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3600 },
    Var { name: "cropprodc_rainfed_sugarcane", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3902 },
    Var { name: "cropprodc_rainfed_temp_corn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3540 },
    Var { name: "cropprodc_rainfed_temp_soybean", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3720 },
    Var { name: "cropprodc_rainfed_trop_corn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3962 },
    Var { name: "cropprodc_rainfed_trop_soybean", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 4022 },
    Var { name: "cropprodc_rainfed_wtwheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3660 },
    Var { name: "cropprodc_unmanagedcrop", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 4084 },
    Var { name: "cropseedc_deficit", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1396 },
    Var { name: "cwdcCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1930 },
    Var { name: "cwdc_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1798 },
    Var { name: "cwdnCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1965 },
    Var { name: "cwdn_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1833 },
    Var { name: "deadcrootc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1127 },
    Var { name: "deadcrootcCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1642 },
    Var { name: "deadcrootc_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1132 },
    Var { name: "deadcrootc_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1647 },
    Var { name: "deadcrootc_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1138 },
    Var { name: "deadcrootc_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1653 },
    Var { name: "deadcrootn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1238 },
    Var { name: "deadcrootnCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1742 },
    Var { name: "deadcrootn_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1243 },
    Var { name: "deadcrootn_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1747 },
    Var { name: "deadcrootn_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1249 },
    Var { name: "deadcrootn_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1753 },
    Var { name: "deadstemc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1096 },
    Var { name: "deadstemcCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1608 },
    Var { name: "deadstemc_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1101 },
    Var { name: "deadstemc_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1613 },
    Var { name: "deadstemc_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1106 },
    Var { name: "deadstemc_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1619 },
    Var { name: "deadstemn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1206 },
    Var { name: "deadstemnCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1708 },
    Var { name: "deadstemn_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1211 },
    Var { name: "deadstemn_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1713 },
    Var { name: "deadstemn_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1217 },
    Var { name: "deadstemn_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1719 },
    Var { name: "discharge", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4712 },
    Var { name: "discharge_rivermouth_regrid", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4717 },
    Var { name: "downreg", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1281 },
    Var { name: "dz_lake", macros: &[], runtime: Some("DEF_USE_Dynamic_Lake"), line: 4458 },
    Var { name: "emis", macros: &[], runtime: None, line: 775 },
    Var { name: "etr", macros: &[], runtime: None, line: 547 },
    Var { name: "etrsha", macros: &[], runtime: None, line: 1020 },
    Var { name: "etrsun", macros: &[], runtime: None, line: 1015 },
    Var { name: "f_h2osfc", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1066 },
    Var { name: "fach", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 946 },
    Var { name: "fert_to_sminn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1416 },
    Var { name: "fertnitro_corn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2568 },
    Var { name: "fertnitro_cotton", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2665 },
    Var { name: "fertnitro_rice1", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2689 },
    Var { name: "fertnitro_rice2", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2713 },
    Var { name: "fertnitro_soybean", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2641 },
    Var { name: "fertnitro_sugarcane", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2737 },
    Var { name: "fertnitro_swheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2592 },
    Var { name: "fertnitro_wwheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2616 },
    Var { name: "fevpa", macros: &[], runtime: None, line: 532 },
    Var { name: "fevpg", macros: &[], runtime: None, line: 557 },
    Var { name: "fevpl", macros: &[], runtime: None, line: 542 },
    Var { name: "fgrnd", macros: &[], runtime: None, line: 562 },
    Var { name: "fh", macros: &[], runtime: None, line: 4539 },
    Var { name: "fhac", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 936 },
    Var { name: "fhah", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 951 },
    Var { name: "fldarea", macros: &[Cond::AnyOf(&["CatchLateralFlow"])], runtime: None, line: 653 },
    Var { name: "floodarea", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4727 },
    Var { name: "floodfrc", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4722 },
    Var { name: "fm", macros: &[], runtime: None, line: 4534 },
    Var { name: "fm10m", macros: &[], runtime: None, line: 4559 },
    Var { name: "fmeta", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 956 },
    Var { name: "forc_pmethanem", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1038 },
    Var { name: "fpg", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1285 },
    Var { name: "fpi", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1289 },
    Var { name: "fq", macros: &[], runtime: None, line: 4544 },
    Var { name: "frcsat", macros: &[], runtime: None, line: 734 },
    Var { name: "frootc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1066 },
    Var { name: "frootcCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1575 },
    Var { name: "frootc_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1071 },
    Var { name: "frootc_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1580 },
    Var { name: "frootc_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1076 },
    Var { name: "frootc_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1586 },
    Var { name: "frootn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1175 },
    Var { name: "frootnCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1675 },
    Var { name: "frootn_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1180 },
    Var { name: "frootn_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1680 },
    Var { name: "frootn_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1185 },
    Var { name: "frootn_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1686 },
    Var { name: "fsena", macros: &[], runtime: None, line: 522 },
    Var { name: "fseng", macros: &[], runtime: None, line: 552 },
    Var { name: "fsengimp", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 901 },
    Var { name: "fsengper", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 906 },
    Var { name: "fsenl", macros: &[], runtime: None, line: 537 },
    Var { name: "fsenroof", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 886 },
    Var { name: "fsenurbl", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 911 },
    Var { name: "fsenwsha", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 896 },
    Var { name: "fsenwsun", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 891 },
    Var { name: "fsno", macros: &[], runtime: None, line: 729 },
    Var { name: "fvehc", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 961 },
    Var { name: "fwst", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 941 },
    Var { name: "gddmaturity", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1371 },
    Var { name: "gddplant", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1376 },
    Var { name: "gdp", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_FIRE)"), line: 1881 },
    Var { name: "gpp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1276 },
    Var { name: "gpp_c3arcgrass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2232 },
    Var { name: "gpp_c3grass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2253 },
    Var { name: "gpp_c4grass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2274 },
    Var { name: "gpp_dbfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2148 },
    Var { name: "gpp_dbftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2127 },
    Var { name: "gpp_dbftrop", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2106 },
    Var { name: "gpp_dbsboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2211 },
    Var { name: "gpp_dbstemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2190 },
    Var { name: "gpp_dnfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2043 },
    Var { name: "gpp_ebftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2085 },
    Var { name: "gpp_ebftrop", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2064 },
    Var { name: "gpp_ebstemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2169 },
    Var { name: "gpp_enfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2022 },
    Var { name: "gpp_enftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2001 },
    Var { name: "grainc", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1144 },
    Var { name: "grainc_storage", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1149 },
    Var { name: "grainc_to_cropprodc", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1407 },
    Var { name: "grainc_to_seed", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1412 },
    Var { name: "grainc_xfer", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1154 },
    Var { name: "grainn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1255 },
    Var { name: "grainn_storage", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1260 },
    Var { name: "grainn_xfer", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1265 },
    Var { name: "green", macros: &[], runtime: None, line: 744 },
    Var { name: "grnd_methane_cond", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 514 },
    Var { name: "grnd_methane_cond_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 986 },
    Var { name: "grnd_methane_cond_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 792 },
    Var { name: "grnd_methane_cond_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 788 },
    Var { name: "groundwater_demand", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1486 },
    Var { name: "groundwater_supply", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1496 },
    Var { name: "gssha", macros: &[], runtime: None, line: 1040 },
    Var { name: "gssun", macros: &[], runtime: None, line: 1035 },
    Var { name: "h2osoi", macros: &[], runtime: None, line: 4354 },
    Var { name: "hdm", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_FIRE)"), line: 1889 },
    Var { name: "hr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1349 },
    Var { name: "hui", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1366 },
    Var { name: "huiswheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2348 },
    Var { name: "inund_flood_depth_patch", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1079 },
    Var { name: "inund_flood_patch", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1075 },
    Var { name: "irrig_method_corn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 2762 },
    Var { name: "irrig_method_cotton", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 2859 },
    Var { name: "irrig_method_rice1", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 2883 },
    Var { name: "irrig_method_rice2", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 2907 },
    Var { name: "irrig_method_soybean", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 2835 },
    Var { name: "irrig_method_sugarcane", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 2931 },
    Var { name: "irrig_method_swheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 2786 },
    Var { name: "irrig_method_wwheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 2810 },
    Var { name: "lai", macros: &[], runtime: None, line: 749 },
    Var { name: "lai_c3arcgrass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2241 },
    Var { name: "lai_c3grass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2262 },
    Var { name: "lai_c4grass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2283 },
    Var { name: "lai_dbfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2157 },
    Var { name: "lai_dbftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2136 },
    Var { name: "lai_dbftrop", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2115 },
    Var { name: "lai_dbsboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2220 },
    Var { name: "lai_dbstemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2199 },
    Var { name: "lai_dnfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2052 },
    Var { name: "lai_ebftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2094 },
    Var { name: "lai_ebftrop", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2073 },
    Var { name: "lai_ebstemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2178 },
    Var { name: "lai_enfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2031 },
    Var { name: "lai_enftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2010 },
    Var { name: "laisha", macros: &[], runtime: None, line: 759 },
    Var { name: "laisun", macros: &[], runtime: None, line: 754 },
    Var { name: "lake_air_o2_flux", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1018 },
    Var { name: "lake_deficit", macros: &[], runtime: Some(".not. DEF_USE_Dynamic_Lake"), line: 4474 },
    Var { name: "lake_icefrac", macros: &[], runtime: None, line: 4468 },
    Var { name: "lake_sed_ch4_flux", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1010 },
    Var { name: "lake_sed_o2_flux", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1014 },
    Var { name: "lake_water_ch4_oxid", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1006 },
    Var { name: "lake_water_ch4_stock", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 998 },
    Var { name: "lake_water_o2_stock", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1002 },
    Var { name: "layer_sat_lag", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1042 },
    Var { name: "ldew", macros: &[], runtime: None, line: 714 },
    Var { name: "leafc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1051 },
    Var { name: "leafcCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1559 },
    Var { name: "leafc_c3arcgrass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2237 },
    Var { name: "leafc_c3grass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2258 },
    Var { name: "leafc_c4grass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2279 },
    Var { name: "leafc_dbfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2153 },
    Var { name: "leafc_dbftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2132 },
    Var { name: "leafc_dbftrop", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2111 },
    Var { name: "leafc_dbsboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2216 },
    Var { name: "leafc_dbstemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2195 },
    Var { name: "leafc_dnfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2048 },
    Var { name: "leafc_ebftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2090 },
    Var { name: "leafc_ebftrop", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2069 },
    Var { name: "leafc_ebstemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2174 },
    Var { name: "leafc_enfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2027 },
    Var { name: "leafc_enftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2006 },
    Var { name: "leafc_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1056 },
    Var { name: "leafc_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1564 },
    Var { name: "leafc_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1061 },
    Var { name: "leafc_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1570 },
    Var { name: "leafn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1160 },
    Var { name: "leafnCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1659 },
    Var { name: "leafn_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1165 },
    Var { name: "leafn_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1664 },
    Var { name: "leafn_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1170 },
    Var { name: "leafn_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1670 },
    Var { name: "lfevpa", macros: &[], runtime: None, line: 527 },
    Var { name: "lfevpgimp", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 921 },
    Var { name: "lfevpgper", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 926 },
    Var { name: "lfevproof", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 916 },
    Var { name: "lfevpurbl", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 931 },
    Var { name: "litr1cCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1900 },
    Var { name: "litr1c_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1768 },
    Var { name: "litr1nCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1935 },
    Var { name: "litr1n_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1803 },
    Var { name: "litr2cCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1905 },
    Var { name: "litr2c_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1773 },
    Var { name: "litr2nCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1940 },
    Var { name: "litr2n_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1808 },
    Var { name: "litr3cCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1910 },
    Var { name: "litr3c_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1778 },
    Var { name: "litr3nCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1945 },
    Var { name: "litr3n_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1813 },
    Var { name: "livecrootc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1111 },
    Var { name: "livecrootcCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1625 },
    Var { name: "livecrootc_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1116 },
    Var { name: "livecrootc_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1630 },
    Var { name: "livecrootc_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1122 },
    Var { name: "livecrootc_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1636 },
    Var { name: "livecrootn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1222 },
    Var { name: "livecrootnCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1725 },
    Var { name: "livecrootn_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1227 },
    Var { name: "livecrootn_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1730 },
    Var { name: "livecrootn_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1233 },
    Var { name: "livecrootn_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1736 },
    Var { name: "livestemc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1081 },
    Var { name: "livestemcCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1591 },
    Var { name: "livestemc_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1086 },
    Var { name: "livestemc_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1596 },
    Var { name: "livestemc_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1091 },
    Var { name: "livestemc_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1602 },
    Var { name: "livestemn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1190 },
    Var { name: "livestemnCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1691 },
    Var { name: "livestemn_storage", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1195 },
    Var { name: "livestemn_storageCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1696 },
    Var { name: "livestemn_xfer", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1201 },
    Var { name: "livestemn_xferCap", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1702 },
    Var { name: "lnfm", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_FIRE)"), line: 1893 },
    Var { name: "manunitro", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2318 },
    Var { name: "methane_B_methanogen", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 529 },
    Var { name: "methane_B_methanogen_dormant", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 537 },
    Var { name: "methane_B_methanotroph", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 533 },
    Var { name: "methane_B_methanotroph_dormant", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 542 },
    Var { name: "methane_aere_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 371 },
    Var { name: "methane_aere_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 655 },
    Var { name: "methane_aere_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 651 },
    Var { name: "methane_balance_residual", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 450 },
    Var { name: "methane_balance_residual_global_with_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 888 },
    Var { name: "methane_ch4_clip_credit", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 454 },
    Var { name: "methane_ch4_clip_credit_global_with_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 896 },
    Var { name: "methane_dfsat_tot", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1062 },
    Var { name: "methane_ebul_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 387 },
    Var { name: "methane_ebul_depth_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 930 },
    Var { name: "methane_ebul_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 671 },
    Var { name: "methane_ebul_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 667 },
    Var { name: "methane_ebul_tot", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 466 },
    Var { name: "methane_ebul_tot_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 966 },
    Var { name: "methane_ebul_tot_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 760 },
    Var { name: "methane_ebul_tot_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 756 },
    Var { name: "methane_finundated", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1070 },
    Var { name: "methane_methanogen_growth_rate", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 564 },
    Var { name: "methane_methanotroph_growth_rate", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 569 },
    Var { name: "methane_microbe_f_O2_methanogen", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 555 },
    Var { name: "methane_microbe_f_S_methanogen", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 551 },
    Var { name: "methane_microbe_f_T_methanogen", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 547 },
    Var { name: "methane_microbe_f_T_methanotroph", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 559 },
    Var { name: "methane_microbial_oxid_potential", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 579 },
    Var { name: "methane_microbial_prod_potential", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 574 },
    Var { name: "methane_oxid_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 359 },
    Var { name: "methane_oxid_depth_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 918 },
    Var { name: "methane_oxid_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 607 },
    Var { name: "methane_oxid_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 603 },
    Var { name: "methane_oxid_tot", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 474 },
    Var { name: "methane_oxid_tot_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 962 },
    Var { name: "methane_oxid_tot_rice", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 490 },
    Var { name: "methane_oxid_tot_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 776 },
    Var { name: "methane_oxid_tot_soil", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 486 },
    Var { name: "methane_oxid_tot_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 772 },
    Var { name: "methane_prod_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 347 },
    Var { name: "methane_prod_depth_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 914 },
    Var { name: "methane_prod_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 599 },
    Var { name: "methane_prod_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 595 },
    Var { name: "methane_prod_tot", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 470 },
    Var { name: "methane_prod_tot_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 958 },
    Var { name: "methane_prod_tot_rice", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 482 },
    Var { name: "methane_prod_tot_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 768 },
    Var { name: "methane_prod_tot_soil", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 478 },
    Var { name: "methane_prod_tot_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 764 },
    Var { name: "methane_soil_finundated", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1117 },
    Var { name: "methane_soil_zwt", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1113 },
    Var { name: "methane_stress", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 395 },
    Var { name: "methane_stress_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 647 },
    Var { name: "methane_stress_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 643 },
    Var { name: "methane_surf_aere", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 408 },
    Var { name: "methane_surf_aere_rice", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 420 },
    Var { name: "methane_surf_aere_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 736 },
    Var { name: "methane_surf_aere_soil", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 416 },
    Var { name: "methane_surf_aere_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 732 },
    Var { name: "methane_surf_diff", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 432 },
    Var { name: "methane_surf_diff_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 938 },
    Var { name: "methane_surf_diff_phys", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 446 },
    Var { name: "methane_surf_diff_rice", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 441 },
    Var { name: "methane_surf_diff_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 752 },
    Var { name: "methane_surf_diff_soil", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 436 },
    Var { name: "methane_surf_diff_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 748 },
    Var { name: "methane_surf_ebul", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 412 },
    Var { name: "methane_surf_ebul_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 934 },
    Var { name: "methane_surf_ebul_rice", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 428 },
    Var { name: "methane_surf_ebul_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 744 },
    Var { name: "methane_surf_ebul_soil", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 424 },
    Var { name: "methane_surf_ebul_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 740 },
    Var { name: "methane_surf_flux_active_total_without_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 864 },
    Var { name: "methane_surf_flux_global_phys_with_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 880 },
    Var { name: "methane_surf_flux_global_total_with_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 872 },
    Var { name: "methane_surf_flux_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 848 },
    Var { name: "methane_surf_flux_lake_intensive", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 952 },
    Var { name: "methane_surf_flux_rice", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 856 },
    Var { name: "methane_surf_flux_soil", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 840 },
    Var { name: "methane_surf_flux_tot", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 824 },
    Var { name: "methane_surf_flux_tot_active", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 399 },
    Var { name: "methane_surf_flux_tot_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 942 },
    Var { name: "methane_surf_flux_tot_phys", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 404 },
    Var { name: "methane_surf_flux_tot_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 728 },
    Var { name: "methane_surf_flux_tot_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 723 },
    Var { name: "methane_surf_flux_wetland", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 832 },
    Var { name: "methane_tran_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 375 },
    Var { name: "methane_tran_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 663 },
    Var { name: "methane_tran_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 659 },
    Var { name: "ndep_to_sminn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1553 },
    Var { name: "net_methane", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 343 },
    Var { name: "net_methane_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 591 },
    Var { name: "net_methane_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 587 },
    Var { name: "npp_c3arcgrass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2245 },
    Var { name: "npp_c3grass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2266 },
    Var { name: "npp_c4grass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2287 },
    Var { name: "npp_dbfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2161 },
    Var { name: "npp_dbftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2140 },
    Var { name: "npp_dbftrop", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2119 },
    Var { name: "npp_dbsboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2224 },
    Var { name: "npp_dbstemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2203 },
    Var { name: "npp_dnfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2056 },
    Var { name: "npp_ebftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2098 },
    Var { name: "npp_ebftrop", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2077 },
    Var { name: "npp_ebstemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2182 },
    Var { name: "npp_enfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2035 },
    Var { name: "npp_enftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2014 },
    Var { name: "npptoleafc_c3arcgrass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2249 },
    Var { name: "npptoleafc_c3grass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2270 },
    Var { name: "npptoleafc_c4grass", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2291 },
    Var { name: "npptoleafc_dbfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2165 },
    Var { name: "npptoleafc_dbftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2144 },
    Var { name: "npptoleafc_dbftrop", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2123 },
    Var { name: "npptoleafc_dbsboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2228 },
    Var { name: "npptoleafc_dbstemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2207 },
    Var { name: "npptoleafc_dnfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2060 },
    Var { name: "npptoleafc_ebftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2102 },
    Var { name: "npptoleafc_ebftrop", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2081 },
    Var { name: "npptoleafc_ebstemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2186 },
    Var { name: "npptoleafc_enfboreal", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2039 },
    Var { name: "npptoleafc_enftemp", macros: &[], runtime: Some("DEF_USE_BGC"), line: 2018 },
    Var { name: "o2_aere_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 379 },
    Var { name: "o2_aere_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 631 },
    Var { name: "o2_aere_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 627 },
    Var { name: "o2_cap_gain", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 462 },
    Var { name: "o2_cap_loss", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 458 },
    Var { name: "o2_decomp_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 351 },
    Var { name: "o2_decomp_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 615 },
    Var { name: "o2_decomp_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 611 },
    Var { name: "o2_oxid_depth", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 363 },
    Var { name: "o2_oxid_depth_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 623 },
    Var { name: "o2_oxid_depth_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 619 },
    Var { name: "o2stress", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 391 },
    Var { name: "o2stress_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 639 },
    Var { name: "o2stress_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 635 },
    Var { name: "o3uptakesha", macros: &[], runtime: Some("DEF_USE_OZONESTRESS"), line: 486 },
    Var { name: "o3uptakesun", macros: &[], runtime: Some("DEF_USE_OZONESTRESS"), line: 482 },
    Var { name: "olrg", macros: &[], runtime: None, line: 582 },
    Var { name: "peatf", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_FIRE)"), line: 1885 },
    Var { name: "plantdate_irrigated_cotton", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3237 },
    Var { name: "plantdate_irrigated_rice", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3297 },
    Var { name: "plantdate_irrigated_spwheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3055 },
    Var { name: "plantdate_irrigated_sugarcane", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3357 },
    Var { name: "plantdate_irrigated_temp_corn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2993 },
    Var { name: "plantdate_irrigated_temp_soybean", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3176 },
    Var { name: "plantdate_irrigated_trop_corn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3417 },
    Var { name: "plantdate_irrigated_trop_soybean", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3478 },
    Var { name: "plantdate_irrigated_wtwheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3115 },
    Var { name: "plantdate_rainfed_cotton", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3207 },
    Var { name: "plantdate_rainfed_rice", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3267 },
    Var { name: "plantdate_rainfed_spwheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3024 },
    Var { name: "plantdate_rainfed_sugarcane", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3327 },
    Var { name: "plantdate_rainfed_temp_corn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 2963 },
    Var { name: "plantdate_rainfed_temp_soybean", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3145 },
    Var { name: "plantdate_rainfed_trop_corn", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3387 },
    Var { name: "plantdate_rainfed_trop_soybean", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3447 },
    Var { name: "plantdate_rainfed_wtwheat", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3085 },
    Var { name: "plantdate_unmanagedcrop", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 3510 },
    Var { name: "qcharge", macros: &[], runtime: Some("(.not.DEF_USE_VariablySaturatedFlow)"), line: 698 },
    Var { name: "qdrip", macros: &[], runtime: None, line: 669 },
    Var { name: "qinfl", macros: &[], runtime: None, line: 664 },
    Var { name: "qintr", macros: &[], runtime: None, line: 659 },
    Var { name: "qlayer", macros: &[], runtime: Some("DEF_USE_VariablySaturatedFlow"), line: 4360 },
    Var { name: "qref", macros: &[], runtime: None, line: 802 },
    Var { name: "qstar", macros: &[], runtime: None, line: 4519 },
    Var { name: "reservoir_supply", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1526 },
    Var { name: "reservoirriver_demand", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1506 },
    Var { name: "reservoirriver_supply", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1516 },
    Var { name: "respc", macros: &[], runtime: None, line: 693 },
    Var { name: "retrasn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1271 },
    Var { name: "rib", macros: &[], runtime: None, line: 4529 },
    Var { name: "river_supply", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1536 },
    Var { name: "rnet", macros: &[], runtime: None, line: 587 },
    Var { name: "rnof", macros: &[], runtime: None, line: 624 },
    Var { name: "rootr", macros: &[], runtime: None, line: 4368 },
    Var { name: "rss", macros: &[], runtime: None, line: 1045 },
    Var { name: "rstfacsha", macros: &[], runtime: None, line: 1030 },
    Var { name: "rstfacsun", macros: &[], runtime: None, line: 1025 },
    Var { name: "rsub", macros: &[], runtime: None, line: 619 },
    Var { name: "rsur", macros: &[], runtime: None, line: 602 },
    Var { name: "rsur_ie", macros: &[Cond::Not("CatchLateralFlow")], runtime: None, line: 613 },
    Var { name: "rsur_se", macros: &[Cond::Not("CatchLateralFlow")], runtime: None, line: 608 },
    Var { name: "runoff_supply", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1546 },
    Var { name: "sabg", macros: &[], runtime: None, line: 577 },
    Var { name: "sabvsha", macros: &[], runtime: None, line: 572 },
    Var { name: "sabvsun", macros: &[], runtime: None, line: 567 },
    Var { name: "sai", macros: &[], runtime: None, line: 764 },
    Var { name: "scv", macros: &[], runtime: None, line: 719 },
    Var { name: "sensors", macros: &[], runtime: None, line: 4671 },
    Var { name: "sigf", macros: &[], runtime: None, line: 739 },
    Var { name: "slope_factor_k", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_TWS_GRACE"), line: 635 },
    Var { name: "sminn_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1838 },
    Var { name: "snowdp", macros: &[], runtime: None, line: 724 },
    Var { name: "soil1cCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1915 },
    Var { name: "soil1c_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1783 },
    Var { name: "soil1nCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1950 },
    Var { name: "soil1n_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1818 },
    Var { name: "soil2cCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1920 },
    Var { name: "soil2c_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1788 },
    Var { name: "soil2nCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1955 },
    Var { name: "soil2n_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1823 },
    Var { name: "soil3cCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1925 },
    Var { name: "soil3c_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1793 },
    Var { name: "soil3nCap_vr", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1960 },
    Var { name: "soil3n_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1828 },
    Var { name: "solnd", macros: &[], runtime: None, line: 4579 },
    Var { name: "solndln", macros: &[], runtime: None, line: 4633 },
    Var { name: "solni", macros: &[], runtime: None, line: 4584 },
    Var { name: "solniln", macros: &[], runtime: None, line: 4638 },
    Var { name: "solvd", macros: &[], runtime: None, line: 4569 },
    Var { name: "solvdln", macros: &[], runtime: None, line: 4623 },
    Var { name: "solvi", macros: &[], runtime: None, line: 4574 },
    Var { name: "solviln", macros: &[], runtime: None, line: 4628 },
    Var { name: "sr", macros: &[], runtime: None, line: 4564 },
    Var { name: "srnd", macros: &[], runtime: None, line: 4599 },
    Var { name: "srndln", macros: &[], runtime: None, line: 4653 },
    Var { name: "srni", macros: &[], runtime: None, line: 4604 },
    Var { name: "srniln", macros: &[], runtime: None, line: 4658 },
    Var { name: "srvd", macros: &[], runtime: None, line: 4589 },
    Var { name: "srvdln", macros: &[], runtime: None, line: 4643 },
    Var { name: "srvi", macros: &[], runtime: None, line: 4594 },
    Var { name: "srviln", macros: &[], runtime: None, line: 4648 },
    Var { name: "sum_deficit_irrig", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1461 },
    Var { name: "sum_irrig", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1451 },
    Var { name: "sum_irrig_count", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1466 },
    Var { name: "t2m_wmo", macros: &[], runtime: Some("DEF_Output_2mWMO"), line: 796 },
    Var { name: "t_brt_fy3d", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_FY"), line: 4295 },
    Var { name: "t_brt_fy3d_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_FY"), line: 4298 },
    Var { name: "t_brt_fy3d_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("(DEF_DA_SM_FY) .and. (DEF_DA_ENS_NUM > 1)"), line: 4302 },
    Var { name: "t_brt_fy3d_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_FY"), line: 4306 },
    Var { name: "t_brt_smap", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_SMAP"), line: 4278 },
    Var { name: "t_brt_smap_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_SMAP"), line: 4281 },
    Var { name: "t_brt_smap_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("(DEF_DA_SM_SMAP) .and. (DEF_DA_ENS_NUM > 1)"), line: 4285 },
    Var { name: "t_brt_smap_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_SM_SMAP"), line: 4289 },
    Var { name: "t_grnd", macros: &[], runtime: None, line: 704 },
    Var { name: "t_lake", macros: &[], runtime: None, line: 4463 },
    Var { name: "t_roof", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 976 },
    Var { name: "t_room", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 966 },
    Var { name: "t_scalar", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1971 },
    Var { name: "t_soisno", macros: &[], runtime: None, line: 4113 },
    Var { name: "t_soisno_5cm", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4222 },
    Var { name: "t_soisno_5cm_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4225 },
    Var { name: "t_soisno_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_ENS_NUM > 1"), line: 4234 },
    Var { name: "t_soisno_ens_5cm_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4243 },
    Var { name: "t_wall", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 981 },
    Var { name: "tafu", macros: &[], runtime: Some("DEF_URBAN_RUN"), line: 971 },
    Var { name: "taux", macros: &[], runtime: None, line: 512 },
    Var { name: "tauy", macros: &[], runtime: None, line: 517 },
    Var { name: "tleaf", macros: &[], runtime: None, line: 709 },
    Var { name: "totcol_methane", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 510 },
    Var { name: "totcol_methane_lake", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 982 },
    Var { name: "totcol_methane_sat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 784 },
    Var { name: "totcol_methane_unsat", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 780 },
    Var { name: "totcolc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1309 },
    Var { name: "totcoln", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1329 },
    Var { name: "totcwdc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1305 },
    Var { name: "totcwdn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1325 },
    Var { name: "totlitc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1297 },
    Var { name: "totlitn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1317 },
    Var { name: "totsoiln_vr", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1843 },
    Var { name: "totsomc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1301 },
    Var { name: "totsomn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1321 },
    Var { name: "totvegc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1293 },
    Var { name: "totvegn", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1313 },
    Var { name: "trad", macros: &[], runtime: None, line: 785 },
    Var { name: "tref", macros: &[], runtime: None, line: 790 },
    Var { name: "tstar", macros: &[], runtime: None, line: 4514 },
    Var { name: "us10m", macros: &[], runtime: None, line: 4549 },
    Var { name: "ustar", macros: &[], runtime: None, line: 4504 },
    Var { name: "ustar2", macros: &[], runtime: None, line: 4509 },
    Var { name: "vegwp", macros: &[], runtime: Some("DEF_USE_PLANTHYDRAULICS"), line: 4374 },
    Var { name: "veloc_riv_regrid", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4708 },
    Var { name: "vf", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("DEF_USE_BGC"), line: 1381 },
    Var { name: "vs10m", macros: &[], runtime: None, line: 4554 },
    Var { name: "w_scalar", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_DiagMatrix)"), line: 1976 },
    Var { name: "wa", macros: &[], runtime: None, line: 4406 },
    Var { name: "wa_inst", macros: &[], runtime: None, line: 4415 },
    Var { name: "wat", macros: &[], runtime: None, line: 674 },
    Var { name: "wat_inst", macros: &[], runtime: None, line: 683 },
    Var { name: "waterstorage", macros: &[Cond::AnyOf(&["CROP"])], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_IRRIGATION)"), line: 1476 },
    Var { name: "wdpth_ucat_regrid", macros: &[Cond::AnyOf(&["GridRiverLakeFlow"])], runtime: None, line: 4704 },
    Var { name: "wdsrf", macros: &[], runtime: None, line: 4420 },
    Var { name: "wdsrf_inst", macros: &[], runtime: None, line: 4429 },
    Var { name: "wetland_frac_patch", macros: &[], runtime: Some("DEF_USE_TRACER"), line: 1083 },
    Var { name: "wetwat", macros: &[], runtime: None, line: 835 },
    Var { name: "wetwat_inst", macros: &[], runtime: None, line: 849 },
    Var { name: "wetzwt", macros: &[], runtime: None, line: 856 },
    Var { name: "wfc", macros: &[], runtime: Some("DEF_USE_BGC"), line: 1854 },
    Var { name: "wice_soisno", macros: &[], runtime: None, line: 4125 },
    Var { name: "wliq_h2osoi_5cm", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4214 },
    Var { name: "wliq_h2osoi_5cm_a", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4217 },
    Var { name: "wliq_soisno", macros: &[], runtime: None, line: 4119 },
    Var { name: "wliq_soisno_ens", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: Some("DEF_DA_ENS_NUM > 1"), line: 4231 },
    Var { name: "wliq_soisno_ens_5cm_ens_std", macros: &[Cond::AnyOf(&["DataAssimilation"])], runtime: None, line: 4240 },
    Var { name: "xerr", macros: &[], runtime: None, line: 592 },
    Var { name: "xwsub", macros: &[Cond::AnyOf(&["CatchLateralFlow"])], runtime: None, line: 648 },
    Var { name: "xwsur", macros: &[Cond::AnyOf(&["CatchLateralFlow"])], runtime: None, line: 643 },
    Var { name: "xy_frl", macros: &[], runtime: None, line: 455 },
    Var { name: "xy_hpbl", macros: &[], runtime: Some("DEF_USE_CBL_HEIGHT"), line: 476 },
    Var { name: "xy_ozone", macros: &[], runtime: Some("(DEF_USE_BGC) .and. (DEF_USE_OZONESTRESS)"), line: 1762 },
    Var { name: "xy_pbot", macros: &[], runtime: None, line: 450 },
    Var { name: "xy_prc", macros: &[], runtime: None, line: 440 },
    Var { name: "xy_prl", macros: &[], runtime: None, line: 445 },
    Var { name: "xy_q", macros: &[], runtime: None, line: 435 },
    Var { name: "xy_rain", macros: &[], runtime: None, line: 465 },
    Var { name: "xy_snow", macros: &[], runtime: None, line: 470 },
    Var { name: "xy_solarin", macros: &[], runtime: None, line: 460 },
    Var { name: "xy_t", macros: &[], runtime: None, line: 430 },
    Var { name: "xy_us", macros: &[], runtime: None, line: 420 },
    Var { name: "xy_vs", macros: &[], runtime: None, line: 425 },
    Var { name: "z0m", macros: &[], runtime: None, line: 780 },
    Var { name: "zerr", macros: &[], runtime: None, line: 597 },
    Var { name: "zol", macros: &[], runtime: None, line: 4524 },
    Var { name: "zwt", macros: &[], runtime: None, line: 4381 },
];
